import { NextRequest, NextResponse } from "next/server";

const BASE_ID=(process.env.AIRTABLE_BASE_ID||"").trim();
const TOKEN=(process.env.AIRTABLE_TOKEN||"").trim();
const INVENTORY_TABLE_ID="tbloOpso4voi5vH6h";
const approvedFields={Category:"fldBHRtqoKKyU7EA5",Subcategory:"fldksRg2j8JH5Exs0"} as const;
type ManagedField=keyof typeof approvedFields;
type Choice={id?:string;name:string;color?:string};
type MetaField={id:string;name:string;type:string;options?:{choices?:Choice[]}};

function headers(){return {Authorization:`Bearer ${TOKEN}`,"Content-Type":"application/json"}}
function configured(){return Boolean(TOKEN&&/^app[A-Za-z0-9]{14}$/.test(BASE_ID))}
function isManagedField(value:unknown):value is ManagedField{return value==="Category"||value==="Subcategory"}
function isAdmin(request:NextRequest){const configuredAdmins=(process.env.EVENTART_ADMIN_EMAILS||"").toLowerCase().split(",").map(v=>v.trim()).filter(Boolean);const email=(request.headers.get("oai-authenticated-user-email")||"").toLowerCase();if(configuredAdmins.length)return configuredAdmins.includes(email);return ["127.0.0.1","localhost","::1"].includes(request.nextUrl.hostname)}
function safeError(data:unknown,status:number){const error=(data as {error?:{type?:unknown;message?:unknown}})?.error;return {type:typeof error?.type==="string"?error.type:`HTTP_${status}`,message:typeof error?.message==="string"?error.message:"Airtable could not update this select field"}}

async function metadata(){const response=await fetch(`https://api.airtable.com/v0/meta/bases/${encodeURIComponent(BASE_ID)}/tables`,{headers:headers(),cache:"no-store"});const data=await response.json() as {tables?:Array<{id:string;name:string;fields:MetaField[]}>};if(!response.ok)throw Object.assign(new Error("Unable to inspect Inventory select options"),{status:response.status,data});const table=data.tables?.find(item=>item.id===INVENTORY_TABLE_ID&&item.name==="Inventory");if(!table)throw new Error("The approved Inventory table could not be verified");for(const [name,id] of Object.entries(approvedFields)){const field=table.fields.find(item=>item.id===id&&item.name===name);if(!field||field.type!=="singleSelect")throw new Error(`The approved Inventory ${name} field could not be verified`)}return table}
async function inventoryRecords(){const records:Array<{fields:Record<string,unknown>}>=[];let offset="";do{const url=new URL(`https://api.airtable.com/v0/${encodeURIComponent(BASE_ID)}/Inventory`);url.searchParams.set("pageSize","100");url.searchParams.append("fields[]","Category");url.searchParams.append("fields[]","Subcategory");if(offset)url.searchParams.set("offset",offset);const response=await fetch(url,{headers:headers(),cache:"no-store"});const data=await response.json() as {records?:Array<{fields:Record<string,unknown>}>;offset?:string};if(!response.ok)throw Object.assign(new Error("Unable to count Inventory option usage"),{status:response.status,data});records.push(...(data.records||[]));offset=data.offset||""}while(offset);return records}
async function state(){const [table,records]=await Promise.all([metadata(),inventoryRecords()]);const fields=Object.fromEntries((Object.keys(approvedFields) as ManagedField[]).map(name=>{const field=table.fields.find(item=>item.id===approvedFields[name])!;const counts=new Map<string,number>();for(const record of records){const value=String(record.fields[name]||"");if(value)counts.set(value,(counts.get(value)||0)+1)}return [name,(field.options?.choices||[]).map(choice=>({name:choice.name,count:counts.get(choice.name)||0}))]}));return {fields,totalRecords:records.length,schemaManagementSupported:false}}

export async function GET(request:NextRequest){if(!configured())return NextResponse.json({error:"Airtable option management is not configured"},{status:400});try{return NextResponse.json({...await state(),canManage:false,managementMessage:isAdmin(request)?"Airtable does not allow single-select choices to be added or deleted through this Web API. A linked Categories and Subcategories structure requires approval before it can be created.":undefined})}catch(error){const safe=error as {status?:number;data?:unknown;message?:string};if(safe.data)console.error("Airtable schema error",safeError(safe.data,safe.status||502));return NextResponse.json({error:safe.message||"Unable to load Inventory options"},{status:safe.status||502})}}

export async function PATCH(request:NextRequest){if(!configured())return NextResponse.json({error:"Airtable option management is not configured"},{status:400});if(!isAdmin(request))return NextResponse.json({error:"Only an EventArt Owner or Admin can manage Inventory options"},{status:403});const body=await request.json() as {field?:unknown;action?:unknown;option?:unknown};if(!isManagedField(body.field)||!["add","delete"].includes(String(body.action)))return NextResponse.json({error:"Only Inventory Category and Subcategory options can be managed"},{status:400});return NextResponse.json({error:"Airtable does not support adding or deleting single-select choices through this Web API. Use linked Inventory Categories and Inventory Subcategories tables for reliable management; those tables have not been created."},{status:409})}
