"use client";

import { Fragment, useCallback, useEffect, useMemo, useState } from "react";
import { useConfirmDialog } from "./ConfirmDialog";

type Row = { id: string; fields: Record<string, unknown> };
type Attachment = { id?: string; url?: string; filename?: string; type?: string };
type Props = { event: Row; onBack: () => void };

const categories = ["Planning","Design","Décor","Florals","Rentals","Catering","Bar Service","Venue","Entertainment","Photography / Video","Stationery / Signage","Transportation","Staffing","Delivery","Setup","Teardown","Taxes","Miscellaneous"];
const statuses = ["Draft","In Review","Sent","Approved","Declined","Expired"];
const clientFields = ["Item / Service","Description","Quantity","Unit Price","Discount","Taxable","Tax Rate","Pre-Tax Client Total","Tax Total","Client Line Total","Category","Custom Category","Optional Item","Included in Proposal"];
const editableFields = ["Item / Service","Description","Category","Custom Category","Quantity","Unit Cost","Unit Price","Discount","Taxable","Tax Rate","Optional Item","Included in Proposal","Notes"];

const num = (v: unknown) => Number(v || 0);
const cad = (v: unknown) => new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" }).format(num(v));
const text = (v: unknown) => Array.isArray(v) ? v.join(", ") : String(v ?? "");
const linked = (v: unknown, id: string) => Array.isArray(v) && v.includes(id);
const requestId = () => `${Date.now()}-${Math.random().toString(36).slice(2)}`;

async function api(method: string, body?: unknown, query?: string) {
  const response = await fetch(query ? `/api/airtable?${query}` : "/api/airtable", { method, headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined });
  const data = await response.json();
  if (!response.ok) throw new Error(typeof data.error === "string" ? data.error : data.error?.message || "Airtable request failed");
  return data;
}

export default function BudgetWorkspace({ event, onBack }: Props) {
  const confirmation = useConfirmDialog();
  const [budget, setBudget] = useState<Row | null>(null);
  const [items, setItems] = useState<Row[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [preview, setPreview] = useState(false);
  const [printRequest, setPrintRequest] = useState<{filename:string}|null>(null);
  const [clientName, setClientName] = useState("");
  const [catalog, setCatalog] = useState<Row[]>([]);
  const [designs, setDesigns] = useState<Row[]>([]);
  const [collapsedCategories, setCollapsedCategories] = useState<Set<string>>(new Set());
  const [dragging, setDragging] = useState<{type:"item"|"category";value:string}|null>(null);
  const [reordering, setReordering] = useState(false);
  const [depositDraft, setDepositDraft] = useState(0);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [b, i, c, s, d] = await Promise.all([api("GET", undefined, "table=Budgets&pageSize=100"), api("GET", undefined, "table=Budget%20Items&pageSize=100"), api("GET", undefined, "table=Clients&pageSize=100"),api("GET",undefined,"table=Service%20Catalog&pageSize=100"),api("GET",undefined,"table=Design%20Board&pageSize=100")]);
      setCatalog((s.records as Row[]).filter(row=>row.fields.Active));
      setDesigns(d.records as Row[]);
      const clientIds = Array.isArray(event.fields.Clients) ? event.fields.Clients : [];
      setClientName((c.records as Row[]).filter((r)=>clientIds.includes(r.id)).map((r)=>text(r.fields["Client Name"])).join(", "));
      const found = (b.records as Row[]).find((r) => linked(r.fields.Event, event.id)) || null;
      setBudget(found);
      setItems(found ? (i.records as Row[]).filter((r) => linked(r.fields.Budget, found.id)).sort((a,b) => num(a.fields["Display Order"])-num(b.fields["Display Order"])) : []);
    } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to load budget"); }
    finally { setLoading(false); }
  }, [event.id]);

  useEffect(() => { load(); }, [load]);
  useEffect(() => { setDepositDraft(num(budget?.fields["Deposit Required"])); }, [budget?.id, budget?.fields["Deposit Required"]]);
  useEffect(()=>{if(!preview||!printRequest)return;let cancelled=false;const prepare=async()=>{await document.fonts?.ready;const images=Array.from(document.querySelectorAll<HTMLImageElement>(".proposal-document img"));await Promise.all(images.map(image=>image.complete?Promise.resolve():new Promise<void>(resolve=>{image.addEventListener("load",()=>resolve(),{once:true});image.addEventListener("error",()=>resolve(),{once:true})})));if(cancelled)return;const previous=document.title;document.title=printRequest.filename;window.print();document.title=previous;setPrintRequest(null)};const timer=window.setTimeout(prepare,120);return()=>{cancelled=true;window.clearTimeout(timer)}},[preview,printRequest]);

  async function createBudget() {
    if (saving) return; setSaving(true);
    try {
      const today = new Date(); const expiry = new Date(today); expiry.setDate(expiry.getDate()+30);
      const created = await api("POST", { table:"Budgets", requestId:requestId(), fields:{ "Budget Name":`${text(event.fields["Event Name"])} Budget`, Event:[event.id], Status:"Draft", "Proposal Number":`EA-${today.getFullYear()}-${String(Date.now()).slice(-5)}`, "Proposal Date":today.toISOString().slice(0,10), "Expiration Date":expiry.toISOString().slice(0,10), Introduction:"Thank you for considering EventArt. We are delighted to present this customized event proposal.", "Scope of Services":"Event planning, design, coordination, and selected event services as detailed below.", "Event Discount":0, "Contingency Type":"Amount", "Contingency Value":0, "Deposit Required":0, "Payment Schedule":"Deposit due upon acceptance. Remaining balance due before the event date.", "Terms and Conditions":"Pricing is valid until the expiration date. Services are confirmed after signed acceptance and deposit.", "Proposal Notes":"" } });
      setBudget(created); setMessage("Budget created and linked to this event.");
    } catch(e){setMessage(e instanceof Error?e.message:"Unable to create budget");} finally{setSaving(false);}
  }

  async function saveBudget(fields: Record<string, unknown>) {
    if (!budget || saving) return; setSaving(true);
    try { const updated=await api("PATCH",{table:"Budgets",id:budget.id,fields});setBudget(updated);setMessage("Budget saved to Airtable."); }
    catch(e){setMessage(e instanceof Error?e.message:"Unable to save");}finally{setSaving(false);}
  }

  async function addItem(source?: Row) {
    if (!budget || saving) return; setSaving(true);
    const s=source?.fields||{};
    const fields:Record<string,unknown>={ "Item / Service":source?`${text(s["Item / Service"])} Copy`:"New item", Budget:[budget.id], Event:[event.id], Category:s.Category||"Planning", "Custom Category":s["Custom Category"]||"", Description:s.Description||"", Quantity:num(s.Quantity)||1, "Unit Cost":num(s["Unit Cost"]), "Unit Price":num(s["Unit Price"]), Discount:num(s.Discount), Taxable:Boolean(s.Taxable), "Tax Rate":num(s["Tax Rate"])||0.13, Notes:s.Notes||"", "Optional Item":Boolean(s["Optional Item"]), "Included in Proposal":source?Boolean(s["Included in Proposal"]):true, "Display Order":items.length+1 };
    try{const created=await api("POST",{table:"Budget Items",requestId:requestId(),fields});setItems((old)=>[...old,created]);setMessage(source?"Item duplicated.":"Budget item added.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to add item");}finally{setSaving(false);}
  }

  async function updateItem(item:Row,fields:Record<string,unknown>){
    try{const updated=await api("PATCH",{table:"Budget Items",id:item.id,fields});setItems((old)=>old.map((r)=>r.id===item.id?updated:r));setMessage("Budget item saved to Airtable.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to update item");}
  }
  async function addCatalogItem(service:Row,optional=true){if(!budget||saving)return;const name=text(service.fields["Service Name"]);if(items.some(item=>text(item.fields["Item / Service"]).toLowerCase()===name.toLowerCase())&&!confirm(`${name} is already in this budget. Add another?`))return;setSaving(true);try{const quantity=name==="Wedding Thank-You Favors"?(num(event.fields["Guest Count"])||1):1;const catalogCategory=text(service.fields.Category)||"Miscellaneous";const fields={"Item / Service":name,Budget:[budget.id],Event:[event.id],Category:categories.includes(catalogCategory)?catalogCategory:"Miscellaneous","Custom Category":catalogCategory,Description:service.fields.Description||"",Quantity:quantity,"Unit Cost":num(service.fields["Standard Unit Cost"]),"Unit Price":num(service.fields["Standard Unit Price"]),Discount:0,Taxable:Boolean(service.fields.Taxable),"Tax Rate":num(service.fields["Tax Rate"])||0.13,"Optional Item":optional,"Included in Proposal":!optional,"Display Order":items.length+1};const created=await api("POST",{table:"Budget Items",requestId:requestId(),fields});setItems(old=>[...old,created]);setMessage(`${name} added ${optional?"as an optional enhancement":"to the proposal"}.`)}catch(error){setMessage(error instanceof Error?error.message:"Unable to add service")}finally{setSaving(false)}}
  async function removeItem(item:Row){if(!await confirmation.confirm({title:"Delete budget item?",name:polished(item.fields["Item / Service"]),body:"This removes the budget item from Airtable and cannot be undone."}))return;try{await api("DELETE",{table:"Budget Items",id:item.id});setItems((old)=>old.filter((r)=>r.id!==item.id));setMessage("Budget item deleted successfully.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to delete item");}}
  async function persistOrder(next:Row[], success:string){
    if(reordering)return;
    const previous=items;setItems(next);setReordering(true);
    const changed=next.map((item,index)=>({item,index,previousOrder:num(previous.find(row=>row.id===item.id)?.fields["Display Order"])})).filter(entry=>num(entry.item.fields["Display Order"])!==entry.index+1);
    const saved:typeof changed=[];
    try{
      const updatedById=new Map<string,Row>();
      for(const entry of changed){const updated=await api("PATCH",{table:"Budget Items",id:entry.item.id,fields:{"Display Order":entry.index+1}});updatedById.set(entry.item.id,updated);saved.push(entry)}
      setItems(next.map((item,index)=>updatedById.get(item.id)||{...item,fields:{...item.fields,"Display Order":index+1}}));setMessage(success);
    }catch(error){await Promise.allSettled(saved.map(entry=>api("PATCH",{table:"Budget Items",id:entry.item.id,fields:{"Display Order":entry.previousOrder}})));setItems(previous);setMessage(`${error instanceof Error?error.message:"Unable to save the new order"} The previous order was restored.`)}finally{setReordering(false)}
  }
  function moveItem(item:Row,delta:number){const category=itemCategory(item);const group=items.filter(row=>itemCategory(row)===category);const index=group.findIndex(row=>row.id===item.id);const target=index+delta;if(target<0||target>=group.length)return;const reordered=[...group];[reordered[index],reordered[target]]=[reordered[target],reordered[index]];let cursor=0;void persistOrder(items.map(row=>itemCategory(row)===category?reordered[cursor++]:row),"Item order saved.")}
  function moveCategory(category:string,delta:number){const names=categoryGroups.map(group=>group.name);const index=names.indexOf(category);const target=index+delta;if(target<0||target>=names.length)return;[names[index],names[target]]=[names[target],names[index]];void persistOrder(names.flatMap(name=>categoryGroups.find(group=>group.name===name)?.rows||[]),"Category order saved.")}
  function dropItem(target:Row){if(!dragging||dragging.type!=="item"||dragging.value===target.id)return;const source=items.find(row=>row.id===dragging.value);if(!source||itemCategory(source)!==itemCategory(target)){setMessage("Move items within their current category. Change Category first to move an item to another section.");setDragging(null);return}const group=items.filter(row=>itemCategory(row)===itemCategory(target));const from=group.findIndex(row=>row.id===source.id);const to=group.findIndex(row=>row.id===target.id);const reordered=[...group];const [moved]=reordered.splice(from,1);reordered.splice(to,0,moved);let cursor=0;setDragging(null);void persistOrder(items.map(row=>itemCategory(row)===itemCategory(target)?reordered[cursor++]:row),"Item order saved.")}
  function dropCategory(target:string){if(!dragging||dragging.type!=="category"||dragging.value===target)return;const names=categoryGroups.map(group=>group.name);const from=names.indexOf(dragging.value);const to=names.indexOf(target);if(from<0||to<0)return;const [moved]=names.splice(from,1);names.splice(to,0,moved);setDragging(null);void persistOrder(names.flatMap(name=>categoryGroups.find(group=>group.name===name)?.rows||[]),"Category order saved.")}
  async function applyDeposit(amount:number){const total=num(budget?.fields["Total Client Price"]);const rounded=Math.round(amount*100)/100;if(rounded<0||rounded>total){setMessage(`Deposit must be between ${cad(0)} and ${cad(total)}.`);return}setDepositDraft(rounded);await saveBudget({"Deposit Required":rounded})}
  function printProposal(){setPreview(true);setPrintRequest({filename:`EventArt_Proposal_${fileSafe(clientName)}_${fileSafe(text(event.fields["Event Name"]))}_${fileSafe(text(budget?.fields["Proposal Number"]))}.pdf`})}

  const categoryGroups=useMemo(()=>groupBudgetItems(items),[items]);

  if(loading)return <div className="budget-loading">Loading Budget & Proposal…</div>;
  if(!budget)return <div className="budget-empty"><button className="back-link" onClick={onBack}>← Back to Events</button><span>EVENTART</span><h1>Budget & Proposal</h1><p>Create a detailed budget and branded proposal for <b>{text(event.fields["Event Name"])}</b>.</p>{message&&<div className="notice">{message}</div>}<button className="gold-button" disabled={saving} onClick={createBudget}>Create Event Budget</button></div>;

  const f=budget.fields;
  return <div className="budget-module">
    <div className="budget-top"><div><button className="back-link" onClick={onBack}>← Events</button><p className="eyebrow">EVENT DETAIL / BUDGET & PROPOSAL</p><h1>{text(event.fields["Event Name"])}</h1><div className="event-meta"><span>{clientName||"Client"}</span><span>{event.fields["Ceremony Date & Time"]?new Date(text(event.fields["Ceremony Date & Time"])).toLocaleDateString("en-CA"):"Date TBD"}</span><span>{text(event.fields["Venue Name"])||"Venue TBD"}</span><span>{text(event.fields["Guest Count"])||"0"} guests</span></div></div><div className="budget-actions"><button onClick={()=>saveBudget({Status:f.Status})}>Save Budget</button><button onClick={()=>downloadCSV(items,event)}>Download CSV</button><button onClick={()=>setPreview(true)}>Preview Proposal</button><button onClick={printProposal}>Print Proposal</button><button className="gold-button" onClick={printProposal}>Download Proposal PDF</button></div></div>
    {message&&<div className="notice">{message}</div>}
    <section className="budget-card proposal-settings"><div className="budget-card-head"><h2>Proposal details</h2><StatusButtons status={text(f.Status)} onChange={(Status)=>saveBudget({Status})}/></div><div className="budget-form-grid">
      <Field label="Proposal number" value={f["Proposal Number"]} onBlur={(v)=>saveBudget({"Proposal Number":v})}/><Field label="Proposal date" type="date" value={f["Proposal Date"]} onBlur={(v)=>saveBudget({"Proposal Date":v})}/><Field label="Expiration date" type="date" value={f["Expiration Date"]} onBlur={(v)=>saveBudget({"Expiration Date":v})}/>
      <Field label="Introduction" area value={f.Introduction} onBlur={(v)=>saveBudget({Introduction:v})}/><Field label="Scope of services" area value={f["Scope of Services"]} onBlur={(v)=>saveBudget({"Scope of Services":v})}/><Field label="Payment schedule" area value={f["Payment Schedule"]} onBlur={(v)=>saveBudget({"Payment Schedule":v})}/><Field label="Terms and conditions" area value={f["Terms and Conditions"]} onBlur={(v)=>saveBudget({"Terms and Conditions":v})}/><Field label="Private proposal notes" area value={f["Proposal Notes"]} onBlur={(v)=>saveBudget({"Proposal Notes":v})}/>
    </div></section>
    {/* eslint-disable-next-line react/no-unescaped-entities */}
    <section className="budget-card budget-items-card"><div className="budget-card-head"><div><h2>Budget line items</h2><p>Tax is shown separately. Client investments are calculated from Airtable's approved pre-tax and tax formulas.</p></div><button className="gold-button" disabled={saving||reordering} onClick={()=>addItem()}>+ Add Budget Item</button></div><div className="budget-table-wrap"><table className="budget-table grouped-budget-table"><thead><tr><th title="Drag or use the move buttons to reorder">Drag</th><th>Service</th><th>Category</th><th>Description</th><th>Qty</th><th>Unit Cost</th><th>Unit Price</th><th>Discount</th><th title="Whether this item is subject to tax">Taxable</th><th>Tax Rate</th><th title="Calculated only on taxable services.">Tax Amount</th><th title="Tax-inclusive client line total. The pre-tax total is shown below it.">Line Total</th><th>Options</th></tr></thead><tbody>{categoryGroups.map((group,groupIndex)=><Fragment key={group.name}><tr className="budget-category-row" data-category={group.name} draggable={!reordering} onDragStart={()=>setDragging({type:"category",value:group.name})} onDragOver={event=>event.preventDefault()} onDrop={()=>dropCategory(group.name)}><th colSpan={13}><div><span className="drag-grip" title="Drag category">⋮⋮</span><button className="category-toggle" onClick={()=>setCollapsedCategories(old=>{const next=new Set(old);next.has(group.name)?next.delete(group.name):next.add(group.name);return next})}>{collapsedCategories.has(group.name)?"▸":"▾"} {group.name}</button><span>{group.rows.length} {group.rows.length===1?"item":"items"}</span><strong>Pre-tax subtotal {cad(group.subtotal)}</strong><span className="category-move"><button disabled={groupIndex===0||reordering} aria-label={`Move ${group.name} up`} onClick={()=>moveCategory(group.name,-1)}>↑</button><button disabled={groupIndex===categoryGroups.length-1||reordering} aria-label={`Move ${group.name} down`} onClick={()=>moveCategory(group.name,1)}>↓</button></span></div></th></tr>{!collapsedCategories.has(group.name)&&group.rows.map((item,itemIndex)=><BudgetRowNew key={item.id} item={item} index={itemIndex} groupSize={group.rows.length} disabled={reordering} onSave={updateItem} onDuplicate={()=>addItem(item)} onDelete={()=>removeItem(item)} onMove={(d)=>moveItem(item,d)} onDragStart={()=>setDragging({type:"item",value:item.id})} onDrop={()=>dropItem(item)}/>)}</Fragment>)}</tbody></table>{!items.length&&<div className="no-records">Add your first customized budget item.</div>}</div></section>
    <section className="budget-card catalog-panel"><div className="budget-card-head"><div><p className="eyebrow">SERVICE CATALOG</p><h2>Enhance Your Celebration</h2></div></div><div className="catalog-grid">{catalog.filter(service=>!items.some(item=>text(item.fields["Item / Service"]).toLowerCase()===text(service.fields["Service Name"]).toLowerCase())).map(service=>{const image=Array.isArray(service.fields.Image)?service.fields.Image[0] as {url?:string}:null;return <article key={service.id}>{image?.url&&<img src={image.url} alt=""/>}<span>{text(service.fields.Category)}</span><h3>{text(service.fields["Service Name"])}</h3><p>{text(service.fields.Description)}</p><b>{cad(service.fields["Standard Unit Price"])} per guest/unit</b><small>{service.fields.Taxable?"Taxable":"Not taxable"} · {service.fields["Optional by Default"]?"Optional by default":"Standard service"}</small><div><button disabled={saving} onClick={()=>addCatalogItem(service,false)}>Add to Budget</button><button className="gold-button" disabled={saving} onClick={()=>addCatalogItem(service,true)}>Add as Optional</button><button onClick={()=>alert(`${text(service.fields["Service Name"])}\n\n${text(service.fields.Description)}\n\n${cad(service.fields["Standard Unit Price"])} per unit`)}>View Details</button></div></article>})}</div></section>
    <section className="budget-summary"><div className="internal-summary"><p className="eyebrow">PRIVATE · EVENTART TEAM</p><h3>Internal business view</h3><p className="summary-help">Internal cost and profitability never appear in the client proposal.</p><Summary label="Total internal cost" value={f["Total Internal Cost"]}/><Summary label="Estimated profit" value={f["Estimated Profit"]}/><Summary label={<>Profit margin <Help text="Estimated profit as a percentage of client revenue before tax."/></>} value={`${(num(f["Profit Margin %"])*100).toFixed(1)}%`} plain/><Summary label="Included services" value={`${items.filter(item=>item.fields["Included in Proposal"]).length}`} plain/><Summary label="Average client price" value={items.length?num(f.Subtotal)/items.length:0}/></div><div className="client-summary"><p className="eyebrow">CLIENT INVESTMENT</p><h3>Financial summary</h3><Summary label="Services Subtotal" value={f.Subtotal}/><Summary label="Item Discounts" value={f["Item Discounts"]}/><div className="summary-edit"><label>Event Discount <Help text="A budget-wide discount applied after all included service line items."/></label><input type="number" min="0" defaultValue={num(f["Event Discount"])} onBlur={(e)=>saveBudget({"Event Discount":Math.max(0,num(e.target.value))})}/></div><ReserveEditor type={text(f["Contingency Type"])} value={num(f["Contingency Value"])} subtotal={num(f.Subtotal)} onSave={saveBudget}/><Summary label="Subtotal Before Tax" value={Math.max(0,num(f["Total Client Price"])-num(f.Tax))}/><Summary label="Tax" value={f.Tax}/><Summary label="Total Client Investment" value={f["Total Client Price"]} total/><Summary label="Deposit Required" value={f["Deposit Required"]}/><Summary label="Remaining Balance" value={f["Remaining Balance"]} total/></div></section>
    <DepositEditor total={num(f["Total Client Price"])} saved={num(f["Deposit Required"])} draft={depositDraft} saving={saving} onDraft={setDepositDraft} onApply={applyDeposit}/>
    {preview&&<LuxuryProposalPreview event={event} budget={budget} items={items} designs={designs} clientName={clientName} onClose={()=>setPreview(false)}/>}
    {confirmation.dialog}
  </div>;
}

function StatusButtons({status,onChange}:{status:string;onChange:(s:string)=>void}){return <div className="status-actions">{statuses.map((s)=><button key={s} className={status===s?"selected":""} onClick={()=>onChange(s)}>{s}</button>)}</div>}
function Field({label,value,onBlur,type="text",area=false}:{label:string;value:unknown;onBlur:(v:string)=>void;type?:string;area?:boolean}){const props={defaultValue:text(value),onBlur:(e:React.FocusEvent<HTMLInputElement|HTMLTextAreaElement>)=>onBlur(e.target.value)};return <label className={area?"wide":""}><span>{label}</span>{area?<textarea {...props}/>:<input type={type} {...props}/>}</label>}
function Summary({label,value,total,plain}:{label:React.ReactNode;value:unknown;total?:boolean;plain?:boolean}){return <div className={total?"summary-line total":"summary-line"}><span>{label}</span><b>{plain?text(value):cad(value)}</b></div>}
function ReserveEditor({type,value,subtotal,onSave}:{type:string;value:number;subtotal:number;onSave:(fields:Record<string,unknown>)=>void}){const [reserveType,setReserveType]=useState(type||"Amount");const [reserveValue,setReserveValue]=useState(value);const calculated=Math.round((reserveType==="Percentage"?subtotal*reserveValue/100:reserveValue)*100)/100;return <div className="reserve-editor"><div><label>Unexpected Event Reserve <span title="A reserve for unforeseen event expenses.">ⓘ</span></label><small>This reserve is intended for unforeseen event-related expenses.</small></div><select value={reserveType} onChange={event=>{const next=event.target.value;setReserveType(next);onSave({"Contingency Type":next})}}><option value="Amount">Fixed Amount</option><option value="Percentage">Percentage</option></select><div className="reserve-value"><span>{reserveType==="Percentage"?"%":"$"}</span><input type="number" min="0" step="0.01" value={reserveValue} onChange={event=>setReserveValue(num(event.target.value))} onBlur={()=>onSave({"Contingency Value":reserveValue})}/></div><b>{reserveType==="Percentage"?`${reserveValue}% of ${cad(subtotal)} = ${cad(calculated)}`:`Reserve: ${cad(calculated)}`}</b></div>}

function BudgetRow({item,index,onSave,onDuplicate,onDelete,onMove}:{item:Row;index:number;onSave:(r:Row,f:Record<string,unknown>)=>void;onDuplicate:()=>void;onDelete:()=>void;onMove:(d:number)=>void}){const f=item.fields;const input=(name:string,type="text")=><input type={type} defaultValue={type==="checkbox"?undefined:text(f[name])} defaultChecked={type==="checkbox"?Boolean(f[name]):undefined} onBlur={(e)=>type!=="checkbox"&&onSave(item,{[name]:type==="number"?num(e.target.value):e.target.value})} onChange={(e)=>type==="checkbox"&&onSave(item,{[name]:e.target.checked})}/>;return <tr><td><button onClick={()=>onMove(-1)}>↑</button><button onClick={()=>onMove(1)}>↓</button></td><td>{input("Item / Service")}</td><td><select defaultValue={text(f.Category)} onChange={(e)=>onSave(item,{Category:e.target.value})}>{categories.map((c)=><option key={c}>{c}</option>)}</select></td><td>{input("Quantity","number")}</td><td>{input("Unit Cost","number")}</td><td>{input("Unit Price","number")}</td><td>{input("Discount","number")}</td><td><label className="tiny-check">{input("Taxable","checkbox")}<span>{(num(f["Tax Rate"])*100).toFixed(0)}%</span></label></td><td><b>{cad(f["Client Line Total"])}</b></td><td><label className="tiny-check">{input("Optional Item","checkbox")}<span>Optional</span></label><label className="tiny-check">{input("Included in Proposal","checkbox")}<span>Include</span></label></td><td><button onClick={onDuplicate}>Duplicate</button><button className="danger" onClick={onDelete}>Delete</button></td></tr>}

function Help({text}:{text:string}){return <span className="help-tip" title={text} aria-label={text}>?</span>}
function DepositEditor({total,saved,draft,saving,onDraft,onApply}:{total:number;saved:number;draft:number;saving:boolean;onDraft:(value:number)=>void;onApply:(value:number)=>void}){const [mode,setMode]=useState<"amount"|"percentage">("amount");const [customPercentage,setCustomPercentage]=useState(total?Math.round(saved/total*10000)/100:0);const preview=mode==="percentage"?Math.round(total*customPercentage)/100:draft;const valid=preview>=0&&preview<=total;const percentage=total?preview/total*100:0;return <section className="budget-card deposit-editor"><div className="budget-card-head"><div><p className="eyebrow">PAYMENT TERMS</p><h2>Deposit Required <Help text="Required to secure your booking."/></h2><p>Choose a suggested deposit or enter a custom amount. Nothing changes until you select Apply Deposit.</p></div><strong>{cad(saved)} saved</strong></div><div className="deposit-quick" aria-label="Suggested deposit percentages">{[25,30,40,50].map(percent=><button key={percent} disabled={saving} onClick={()=>{setMode("percentage");setCustomPercentage(percent);onDraft(Math.round(total*percent)/100)}}>{percent}%<small>{cad(total*percent/100)}</small></button>)}</div><div className="deposit-custom"><div className="deposit-mode"><button className={mode==="amount"?"active":""} onClick={()=>setMode("amount")}>Custom amount</button><button className={mode==="percentage"?"active":""} onClick={()=>setMode("percentage")}>Custom percentage</button></div>{mode==="amount"?<label><span>Deposit amount</span><div><b>$</b><input type="number" min="0" max={total} step="0.01" value={draft} onChange={event=>onDraft(num(event.target.value))}/></div></label>:<label><span>Deposit percentage</span><div><input type="number" min="0" max="100" step="0.01" value={customPercentage} onChange={event=>{const next=num(event.target.value);setCustomPercentage(next);onDraft(Math.round(total*next)/100)}}/><b>%</b></div></label>}<div className="deposit-preview"><span>Deposit preview</span><b>{cad(preview)}</b><small>{percentage.toFixed(2)}% of {cad(total)}</small></div><div className="deposit-preview"><span>Remaining balance</span><b>{cad(Math.max(0,total-preview))}</b><small>Updates after the deposit is applied</small></div></div>{!valid&&<p className="deposit-error">Deposit cannot be negative or greater than the Total Client Investment.</p>}<button className="gold-button deposit-apply" disabled={saving||!valid||preview===saved} onClick={()=>onApply(preview)}>{saving?"Saving…":"Apply Deposit"}</button></section>}
function itemCategory(item:Row){return polished(item.fields.Category||item.fields["Custom Category"])||"Uncategorized"}
function groupBudgetItems(items:Row[]){const groups:Record<string,Row[]>={};for(const item of items){const category=itemCategory(item);(groups[category]??=[]).push(item)}return Object.entries(groups).map(([name,rows])=>({name,rows,subtotal:rows.reduce((sum,row)=>sum+num(row.fields["Pre-Tax Client Total"]),0)}))}
const descriptionHelp="Describe exactly what is included in this service. This wording will appear in the client proposal.";
function DescriptionEditor({item,onSave}:{item:Row;onSave:(r:Row,f:Record<string,unknown>)=>void}){const name=text(item.fields["Item / Service"])||"budget item";return <label className="budget-description-editor"><textarea aria-label={`Description for ${name}`} defaultValue={text(item.fields.Description)} onBlur={event=>onSave(item,{Description:event.target.value})}/><small>{descriptionHelp}</small></label>}
function BudgetRowNew({item,index,groupSize,disabled,onSave,onDuplicate,onDelete,onMove,onDragStart,onDrop}:{item:Row;index:number;groupSize:number;disabled:boolean;onSave:(r:Row,f:Record<string,unknown>)=>void;onDuplicate:()=>void;onDelete:()=>void;onMove:(d:number)=>void;onDragStart:()=>void;onDrop:()=>void}){const f=item.fields;const input=(name:string,type="text",extra:Record<string,unknown>={})=><input {...extra} type={type} defaultValue={type==="checkbox"?undefined:text(f[name])} defaultChecked={type==="checkbox"?Boolean(f[name]):undefined} onBlur={(e)=>type!=="checkbox"&&onSave(item,{[name]:type==="number"?Math.max(0,num(e.target.value)):e.target.value})} onChange={(e)=>type==="checkbox"&&onSave(item,{[name]:e.target.checked})}/>;return <tr className="budget-item-row" draggable={!disabled} onDragStart={onDragStart} onDragOver={event=>event.preventDefault()} onDrop={onDrop}><td><span className="drag-grip" title="Drag item">⋮⋮</span><div className="item-move"><button disabled={disabled||index===0} aria-label="Move item up" onClick={()=>onMove(-1)}>↑</button><button disabled={disabled||index===groupSize-1} aria-label="Move item down" onClick={()=>onMove(1)}>↓</button></div></td><td>{input("Item / Service")}<div className="mobile-budget-description"><DescriptionEditor item={item} onSave={onSave}/></div></td><td><select defaultValue={text(f.Category)} onChange={(e)=>onSave(item,{Category:e.target.value})}>{categories.map((c)=><option key={c}>{c}</option>)}</select></td><td className="budget-description-cell"><DescriptionEditor item={item} onSave={onSave}/></td><td>{input("Quantity","number",{min:0,step:1})}</td><td>{input("Unit Cost","number",{min:0,step:.01})}</td><td>{input("Unit Price","number",{min:0,step:.01})}</td><td>{input("Discount","number",{min:0,step:.01})}</td><td><label className="tiny-check">{input("Taxable","checkbox")}<span>{f.Taxable?"Yes":"No"}</span></label></td><td>{input("Tax Rate","number",{min:0,max:1,step:.01})}<small className="cell-note">{(num(f["Tax Rate"])*100).toFixed(0)}%</small></td><td><b>{cad(f["Tax Total"])}</b></td><td><b>{cad(f["Client Line Total"])}</b><small className="cell-note">Pre-tax {cad(f["Pre-Tax Client Total"])}</small></td><td><div className="row-options"><label className="tiny-check">{input("Optional Item","checkbox")}<span>Optional</span></label><label className="tiny-check">{input("Included in Proposal","checkbox")}<span>Include</span></label><button onClick={onDuplicate}>Duplicate</button><button className="danger" onClick={onDelete}>Delete</button></div></td></tr>}
function polished(value:unknown){return text(value).replaceAll("_"," ").replace(/D(?:Ã‰|Ã©|É|�)?COR/gi,"DECOR").replace(/([.!?])(?=[A-Z])/g,"$1 ").replace(/\s+/g," ").trim()}
function blocks(value:unknown){return polished(value).split(/\r?\n+/).map(v=>v.trim()).filter(Boolean)}
function proposalDescription(value:unknown){return text(value).replace(/\r\n/g,"\n").trim()}
type ServiceSection={key:string;title:string;intro:string;included:string[];note?:string;match:string[]};
const serviceLibrary:ServiceSection[]=[
 {key:"planning",title:"Planning & Coordination",intro:"Thoughtful planning is the foundation of an effortless celebration. We guide each decision with clarity, precision and calm, keeping every detail aligned from the first consultation through the wedding day.",included:["Planning consultations","Budget management","Timeline development","Vendor communication","Logistics planning","Wedding day coordination"],match:["planning","coordination","timeline","logistics"]},
 {key:"design",title:"Event Design",intro:"We create a cohesive luxury design that reflects your story through intentional colour, texture, scale and atmosphere.",included:["Design concept","Mood board","Colour palette","Layout planning","Rental styling","Decorative styling"],match:["design","styling","decor","décor","mood","rental"]},
 {key:"ceremony",title:"Ceremony Styling",intro:"A refined ceremony setting designed to frame the most meaningful moments of your celebration.",included:["Ceremony backdrop","Aisle styling","Welcome display","Reserved seating","Floral accents","Candle styling"],match:["ceremony","aisle","backdrop"]},
 {key:"reception",title:"Reception Design",intro:"An inviting reception environment layered with elegant details and considered guest experiences.",included:["Head table","Guest tables","Cake display","Seating chart","Welcome display","Photo backdrop","Lounge styling"],match:["reception","head table","guest table","cake display","seating chart","lounge"]},
 {key:"floral",title:"Floral Coordination",intro:"EventArt coordinates floral details with your selected floral professional so every installation supports the overall design vision.",included:["Bouquet coordination","Ceremony florals","Reception florals","Cake florals","Floral installation"],match:["floral","flower","bouquet"]},
 {key:"vendor",title:"Vendor Management",intro:"We act as the primary point of contact for your creative team, coordinating schedules, deliveries and expectations with discretion.",included:["Vendor scheduling","Delivery coordination","Setup supervision","Communication","Timeline management"],match:["vendor","delivery coordination"]},
 {key:"entertainment",title:"Entertainment",intro:"We coordinate the entertainment experience so every cue, announcement and signature moment flows naturally.",included:["DJ coordination","Ceremony music","Reception schedule","First dance","Microphones"],match:["entertainment","dj","music","microphone"]},
 {key:"photography",title:"Photography",intro:"We collaborate with your photography team to protect time for meaningful portraits while keeping the celebration on schedule.",included:["Photography timeline","Family portraits","Ceremony coordination","Reception coordination"],match:["photography","photo","portrait","video"]},
 {key:"management",title:"Wedding Day Management",intro:"Our premium on-site management service allows you and your guests to remain fully present while EventArt quietly directs every moving part.",included:["Complete on-site management","Vendor supervision","Ceremony coordination","Reception coordination","Guest assistance","Timeline execution","Problem resolution","Final walkthrough"],match:["wedding day","day of","on-site","onsite","event management"]},
 {key:"setup",title:"Setup & Breakdown",intro:"Our team oversees installation and collection with meticulous care, ensuring the finished setting meets the EventArt standard.",included:["Decor installation","Styling","Quality inspection","Breakdown","Inventory collection"],match:["setup","set up","teardown","breakdown","installation"]}
];
function selectedServiceSections(items:Row[]){const haystack=items.map(i=>`${polished(i.fields.Category)} ${polished(i.fields["Custom Category"])} ${polished(i.fields["Item / Service"])} ${polished(i.fields.Description)}`).join(" ").toLowerCase();return serviceLibrary.filter(section=>section.match.some(term=>haystack.includes(term)))}
function chunked<T>(values:T[],size:number){const result:T[][]=[];for(let index=0;index<values.length;index+=size)result.push(values.slice(index,index+size));return result.length?result:[[]]}
const inspirationPriority=["Mood Board","Ceremony Design","Reception Design","Floral Design","Table Design","AI Rendering","SketchUp Mockup","Welcome Sign","Seating Chart Sign"];
function inspirationImages(records:Row[],eventId:string){return records.filter(record=>linked(record.fields.Event,eventId)&&Boolean(record.fields["Visible to Client"])).sort((a,b)=>{const ai=inspirationPriority.indexOf(text(a.fields["Design Category"]));const bi=inspirationPriority.indexOf(text(b.fields["Design Category"]));return (ai<0?999:ai)-(bi<0?999:bi)}).flatMap(record=>{const preview=Array.isArray(record.fields["Preview Image"])?record.fields["Preview Image"] as Attachment[]:[];const design=Array.isArray(record.fields["Design File"])?record.fields["Design File"] as Attachment[]:[];const attachments=preview.length?preview:design.filter(file=>file.type?.startsWith("image/"));return attachments.filter(file=>file.url&&(file.type?.startsWith("image/")||/\.(jpe?g|png|webp)(?:\?|$)/i.test(file.url))).map(file=>({id:file.id||file.url!,url:file.url!,caption:polished(record.fields["Design Title"]||record.fields["Design Category"]),category:polished(record.fields["Design Category"])}))}).slice(0,6)}
function eventExperienceIntro(event:Row,clientName:string,date:string){const who=polished(clientName);const eventType=polished(event.fields["Event Type"]);const venue=polished(event.fields["Venue Name"]);const theme=polished(event.fields.Theme);const palette=polished(event.fields["Color Palette"]);const guests=polished(event.fields["Guest Count"]);const first=`${who?`For ${who}, `:""}EventArt will create ${eventType?`a refined ${eventType.toLowerCase()}`:"a refined celebration"}${venue?` at ${venue}`:""}${event.fields["Ceremony Date & Time"]?` on ${date}`:""}.`;const details=[theme?`the ${theme} theme`:"",palette?`a ${palette} colour palette`:""].filter(Boolean);const direction=details.length?`${details.join(" and ")} will guide the design`:"Every detail will be thoughtfully considered";const second=details.length||guests?`${direction.replace(/^./,character=>character.toUpperCase())}${guests?` for ${guests} guests`:""}.`:"";return `${first}${second?` ${second}`:""}`}
function serviceIntroduction(service:ServiceSection,clientName:string){const intro=service.intro.startsWith("EventArt")?service.intro:service.intro.replace(/^./,character=>character.toLowerCase());return clientName?`For ${polished(clientName)}, ${intro}`:service.intro}
function paymentInstallments(value:unknown){return blocks(value).flatMap(paragraph=>{const matches=paragraph.match(/(?:^|\s)(\d+(?:\.\d+)?%\s+.*?)(?=\s+\d+(?:\.\d+)?%\s+|$)/g);return matches&&matches.length>1?matches.map(entry=>entry.trim()):[paragraph]})}
const termTitles=["Proposal Validity","Booking Confirmation","Additional Services","Vendor Coordination","Client Responsibilities","Changes to the Event","Cancellation Policy","Force Majeure","Event Schedule","Overtime","Damages","Rentals","Photography & Marketing","Limitation of Liability"];
type TermClause={heading:string;body:string};
function termClauses(value:unknown):TermClause[]{const stored=text(value).replace(/\r\n/g,"\n").trim();if(!stored)return[];const knownTitles=termTitles.map(title=>title.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|");const boundary=new RegExp(`\\s+(?=\\d+\\.\\s+(?:${knownTitles})(?:\\s|$))`,"g");return stored.split(boundary).map(entry=>entry.replace(/^\d+\.\s*/,"").trim()).filter(Boolean).map(entry=>{const heading=termTitles.find(candidate=>entry.startsWith(candidate))||"";return{heading,body:heading?entry.slice(heading.length).trimStart():entry}})}
function TermClauseView({clause,number}:{clause:TermClause;number:number}){return <section className={`term-clause ${clause.body.length<430?"short-term-clause":""}`}><h3><span>{String(number).padStart(2,"0")}</span> - {clause.heading||"Terms"}</h3><p>{clause.body}</p></section>}
function LuxuryProposalPreview({event,budget,items,designs,clientName,onClose}:{event:Row;budget:Row;items:Row[];designs:Row[];clientName:string;onClose:()=>void}){
 const f=budget.fields;const included=items.filter(item=>item.fields["Included in Proposal"]);const optional=items.filter(item=>item.fields["Optional Item"]&&!item.fields["Included in Proposal"]);const date=event.fields["Ceremony Date & Time"]?new Date(text(event.fields["Ceremony Date & Time"])).toLocaleDateString("en-CA",{year:"numeric",month:"long",day:"numeric"}):"Date to be confirmed";const selectedServices=selectedServiceSections(included);const inspiration=inspirationImages(designs,event.id);const terms=termClauses(f["Terms and Conditions"]);const servicePages=selectedServices.length?chunked(selectedServices,3):[];const includedPages=chunked(included,6);if(!includedPages.length)includedPages.push([]);const lastIncludedPage=includedPages[includedPages.length-1]||[];const inlineOptional=optional.length>0&&optional.length<=2&&lastIncludedPage.length<=2;const optionalPages=optional.length&&!inlineOptional?chunked(optional,7):[];const termPages=terms.length?[terms.slice(0,4),...(terms.length>4?chunked(terms.slice(4),5):[])]:[[]];const designPageCount=inspiration.length?1:0;const serviceStart=3+designPageCount;const includedStart=serviceStart+servicePages.length;const optionalStart=includedStart+includedPages.length;const termsStart=optionalStart+optionalPages.length;const acceptanceNumber=termsStart+termPages.length;const total=acceptanceNumber;const personalizedIntro=eventExperienceIntro(event,clientName,date);
 return <div className="proposal-overlay luxury-proposal"><button className="proposal-scrim" onClick={onClose}/><button className="proposal-close floating" onClick={onClose}>×</button><article id="proposal-print-root" className="proposal-document">
  <section className="proposal-page proposal-cover"><div className="proposal-cover-center"><img src="/eventart-logo-transparent.png" alt="EventArt"/><div className="cover-rule"/><p>WEDDING PROPOSAL</p><h1>{polished(clientName||event.fields["Event Name"]||"Your Celebration")}</h1><dl><div><dt>Date</dt><dd>{date}</dd></div><div><dt>Venue</dt><dd>{polished(event.fields["Venue Name"])||"To be confirmed"}</dd></div><div><dt>Proposal</dt><dd>{polished(f["Proposal Number"])}</dd></div></dl></div><footer><b>Prepared by EventArt</b><span>Luxury Event Design & Styling</span></footer></section>
   <ProposalPage number={2} total={total} proposal={text(f["Proposal Number"])} title="Your Celebration"><div className="editorial-intro">{blocks(f.Introduction).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><div className="detail-panel">{[["Client",clientName],["Event",polished(event.fields["Event Name"])],["Date",date],["Venue",polished(event.fields["Venue Name"])],["Guest count",text(event.fields["Guest Count"])],["Proposal",text(f["Proposal Number"])],["Issue date",text(f["Proposal Date"])],["Valid until",text(f["Expiration Date"])]].filter(entry=>entry[1]).map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div><h3 className="gold-heading">Event Vision</h3><p>{personalizedIntro}</p></ProposalPage>
   {inspiration.length>0&&<ProposalPage number={3} total={total} proposal={text(f["Proposal Number"])} title="Design Inspiration" className="design-inspiration-page"><p className="design-inspiration-intro">A curated visual direction for your celebration.</p><div className={`proposal-inspiration-grid count-${inspiration.length}`}>{inspiration.map(image=><figure key={image.id}><img src={image.url} alt={image.caption}/><figcaption><span>{image.category}</span><b>{image.caption}</b></figcaption></figure>)}</div></ProposalPage>}
   {servicePages.map((page,pageIndex)=>{const last=pageIndex===servicePages.length-1;return <ProposalPage key={`experience-${pageIndex}`} number={serviceStart+pageIndex} total={total} proposal={text(f["Proposal Number"])} title="Your Event Experience">{pageIndex===0&&<p className="experience-intro">{personalizedIntro}</p>}<div className="service-library">{page.map((service,index)=><ServiceExperience key={service.key} service={service} clientName={clientName} index={pageIndex*3+index}/>)}</div>{last&&<><h3 className="gold-heading">What You Will Receive</h3><div className="deliverable-cards">{selectedServices.map(service=><div key={service.key}>✓ {service.title}</div>)}</div></>}{last&&optional.length>0&&<section className="available-request"><h3>Available Upon Request</h3><p>The following services may be added to your celebration if desired.</p><ul>{optional.map(item=><li key={item.id}>{polished(item.fields["Item / Service"])}</li>)}</ul></section>}</ProposalPage>})}
  {includedPages.map((page,pageIndex)=>{const last=pageIndex===includedPages.length-1;return <ProposalPage key={`included-${pageIndex}`} className={last?"investment-summary-page":""} number={includedStart+pageIndex} total={total} proposal={text(f["Proposal Number"])} title={pageIndex?"Services & Investment - Continued":"Services & Investment"}><ProposalInvestmentTable items={page}/>{last&&<div className="investment-card"><h3>Investment Summary</h3><Summary label="Services Subtotal" value={f.Subtotal}/><Summary label="Item Discounts" value={f["Item Discounts"]}/><Summary label="Event Discount" value={f["Event Discount"]}/>{num(f.Contingency)>0&&<Summary label="Unexpected Event Reserve" value={f.Contingency}/>}<Summary label="Subtotal Before Tax" value={Math.max(0,num(f["Total Client Price"])-num(f.Tax))}/><Summary label="Tax" value={f.Tax}/><Summary label="Total Client Investment" value={f["Total Client Price"]} total/><div className="deposit-summary"><Summary label="Deposit Required" value={f["Deposit Required"]}/><Summary label="Remaining Balance" value={f["Remaining Balance"]}/></div></div>}{last&&inlineOptional&&<section className="inline-optional-enhancements"><h3>Optional Enhancements</h3><p className="quiet-note">These enhancements may be added to your celebration upon request and are not included in the current proposal total.</p><ProposalInvestmentTable items={optional} optional/></section>}</ProposalPage>})}
  {optionalPages.map((page,pageIndex)=><ProposalPage key={`optional-${pageIndex}`} className="optional-enhancements-page" number={optionalStart+pageIndex} total={total} proposal={text(f["Proposal Number"])} title={pageIndex?"Optional Enhancements - Continued":"Optional Enhancements"}>{pageIndex===0&&<p className="quiet-note">These enhancements may be added to your celebration upon request and are not included in the current proposal total.</p>}<ProposalInvestmentTable items={page} optional/></ProposalPage>)}
   {termPages.map((page,pageIndex)=>{const start=termPages.slice(0,pageIndex).reduce((count,entries)=>count+entries.length,1);return <ProposalPage key={`terms-${pageIndex}`} className={`terms-page ${pageIndex?"terms-continuation-page":""}`} number={termsStart+pageIndex} total={total} proposal={text(f["Proposal Number"])} title={pageIndex?"Terms & Conditions - Continued":"Payment & Terms"}>{pageIndex===0&&<><h3 className="gold-heading">Payment Schedule</h3><div className="payment-installments">{paymentInstallments(f["Payment Schedule"]).map((paragraph,index)=><div key={index}><span>Installment {String(index+1).padStart(2,"0")}</span><p>{paragraph}</p></div>)}</div><h3 className="gold-heading terms-heading">Terms & Conditions</h3></>}<div className="terms-clauses">{page.map((clause,index)=><TermClauseView key={`${start+index}-${clause.heading}`} clause={clause} number={start+index}/>)}</div></ProposalPage>})}
   <ProposalPage number={acceptanceNumber} total={total} proposal={text(f["Proposal Number"])} title="With Appreciation"><p className="closing-message">Thank you for considering EventArt to be part of one of the most meaningful days of your lives. We are honored by the opportunity to design an experience that reflects your story, your style and your celebration.</p><p>This proposal is valid until <b>{text(f["Expiration Date"])||"the stated expiration date"}</b>. By signing below, the client confirms acceptance of the services, investment and terms presented in this proposal.</p><div className="signature-grid"><div><span>{clientName||"Client name"}</span><b>Client name</b></div><div><span>&nbsp;</span><b>Client signature</b></div><div><span>&nbsp;</span><b>Date</b></div><div><span>EventArt</span><b>EventArt representative</b></div><div><span>&nbsp;</span><b>Signature</b></div><div><span>&nbsp;</span><b>Date</b></div></div></ProposalPage>
 </article></div>
}
function ServiceExperience({service,index,clientName}:{service:ServiceSection;index:number;clientName:string}){return <section className={`service-experience ${service.key==="management"?"premium-service":""}`}><div className="service-icon">{String(index+1).padStart(2,"0")}</div><div><h3>{service.title}</h3><p>{serviceIntroduction(service,clientName)}</p><ul>{service.included.map(item=><li key={item}>{item}</li>)}</ul>{service.note&&<p className="service-note">{service.note}</p>}</div></section>}
function ProposalPage({number,total,proposal,title,children,className=""}:{number:number;total:number;proposal:string;title:string;children:React.ReactNode;className?:string}){return <section className={`proposal-page proposal-interior ${className}`}><header><img src="/eventart-logo-transparent.png" alt="EventArt"/><div><span>EVENTART</span><small>Luxury Event Design & Styling</small></div></header><h2>{title}</h2>{children}<footer><img className="proposal-footer-logo" src="/eventart-logo-transparent.png" alt=""/><span>EventArt · Luxury Event Design & Styling</span><span>{proposal} · Page {number} of {total}</span></footer></section>}
function ProposalInvestmentTable({items,optional=false}:{items:Row[];optional?:boolean}){const grouped=Object.entries(items.reduce<Record<string,Row[]>>((groups,item)=>{const category=polished(item.fields["Custom Category"]||item.fields.Category)||"Services";(groups[category]??=[]).push(item);return groups},{}));return <div className={`proposal-table-wrap ${optional?"optional-table":""}`}><table className="proposal-investment-table"><colgroup><col className="proposal-col-service"/><col className="proposal-col-description"/><col className="proposal-col-quantity"/><col className="proposal-col-unit-price"/><col className="proposal-col-investment"/></colgroup><thead><tr><th>{optional?"Enhancement":"Service"}</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Investment</th></tr></thead><tbody>{grouped.map(([category,rows])=><Fragment key={category}><tr className="proposal-category-row"><th colSpan={5}>{category}</th></tr>{rows.map(item=><tr key={item.id}><td><b>{polished(item.fields["Item / Service"])||"Service"}</b></td><td className="proposal-description">{proposalDescription(item.fields.Description)||"—"}</td><td>{num(item.fields.Quantity)}</td><td>{cad(item.fields["Unit Price"])}</td><td><strong>{cad(optional?Math.max(0,num(item.fields.Quantity)*num(item.fields["Unit Price"])-num(item.fields.Discount)):item.fields["Pre-Tax Client Total"])}</strong></td></tr>)}</Fragment>)}</tbody></table>{optional&&<p className="optional-tax-note">Applicable taxes will be calculated only if this enhancement is added to your proposal.</p>}</div>}

function downloadCSV(items:Row[],event:Row){const heads=["Display Order",...editableFields,"Internal Cost Total","Client Line Total"] ;const rows=items.map((i)=>heads.map((h)=>`"${text(i.fields[h]).replaceAll('"','""')}"`).join(","));const blob=new Blob([[heads.join(","),...rows].join("\r\n")],{type:"text/csv"});downloadBlob(blob,`EventArt_Budget_${fileSafe(text(event.fields["Event Name"]))}.csv`)}
function fileSafe(v:string){return v.replace(/[^A-Za-z0-9_-]+/g,"_").replace(/_+/g,"_").replace(/^_+|_+$/g,"")||"Event"}
function downloadBlob(blob:Blob,name:string){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.style.display="none";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
