"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import RecordForm,{AirtableRow} from "./RecordForm";

type Props={event?:AirtableRow;embedded?:boolean;onOpenEvent?:(event:AirtableRow)=>void};
const categories=["Mood Board","Ceremony Design","Reception Design","Floor Plan","SketchUp Mockup","AI Rendering","Welcome Sign","Seating Chart Sign","Menu","Table Design","Floral Design","Rental Selection","Other"];
const statuses=["Draft","Internal Review","Sent to Client","Changes Requested","Approved","Final"];
const groupOrder=["Event Vision","Mood Boards","Colour Palette","Ceremony","Reception","Table Styling","Florals","Signage","Floor Plans","SketchUp & 3D","AI Renderings","Rental Selections"];
const groupFor=(category:string)=>({"Mood Board":"Mood Boards","Ceremony Design":"Ceremony","Reception Design":"Reception","Floor Plan":"Floor Plans","SketchUp Mockup":"SketchUp & 3D","AI Rendering":"AI Renderings","Welcome Sign":"Signage","Seating Chart Sign":"Signage",Menu:"Signage","Table Design":"Table Styling","Floral Design":"Florals","Rental Selection":"Rental Selections"}[category]||"Event Vision");
const text=(v:unknown)=>Array.isArray(v)?v.join(", "):String(v??"");
const attachmentUrl=(v:unknown)=>Array.isArray(v)&&v.length&&typeof v[0]==="object"?String((v[0] as {url?:unknown}).url||""):"";
const requestId=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;
async function api(method:string,body?:unknown,query=""){const r=await fetch(`/api/airtable${query?`?${query}`:""}`,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(typeof d.error==="string"?d.error:d.error?.message||"Unable to complete this action");return d}

export default function DesignStudio({event,embedded=false,onOpenEvent}:Props){
 const [designs,setDesigns]=useState<AirtableRow[]>([]),[events,setEvents]=useState<AirtableRow[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[eventFilter,setEventFilter]=useState("All"),[category,setCategory]=useState("All"),[status,setStatus]=useState("All"),[sort,setSort]=useState("recent"),[form,setForm]=useState<{record?:AirtableRow}|null>(null),[detail,setDetail]=useState<AirtableRow|null>(null),[clientMode,setClientMode]=useState(false),[notice,setNotice]=useState<{kind:"success"|"error";text:string}|null>(null),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const [d,e]=await Promise.all([api("GET",undefined,"table=Design%20Board&pageSize=100"),api("GET",undefined,"table=Events&pageSize=100")]);setDesigns(d.records||[]);setEvents(e.records||[])}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Unable to load designs"})}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const eventName=(record:AirtableRow)=>events.filter(e=>Array.isArray(record.fields.Event)&&record.fields.Event.includes(e.id)).map(e=>text(e.fields["Event Name"])).join(", ");
 const filtered=useMemo(()=>designs.filter(d=>!event||Array.isArray(d.fields.Event)&&d.fields.Event.includes(event.id)).filter(d=>eventFilter==="All"||Array.isArray(d.fields.Event)&&d.fields.Event.includes(eventFilter)).filter(d=>category==="All"||d.fields["Design Category"]===category).filter(d=>status==="All"||d.fields["Approval Status"]===status).filter(d=>JSON.stringify(d.fields).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="title"?text(a.fields["Design Title"]).localeCompare(text(b.fields["Design Title"])):sort==="version"?Number(b.fields.Version||0)-Number(a.fields.Version||0):sort==="event"?eventName(a).localeCompare(eventName(b)):text(b.fields["Date Submitted"]||b.id).localeCompare(text(a.fields["Date Submitted"]||a.id))),[designs,event,eventFilter,category,status,query,sort,events]);
 const groups=groupOrder.map(name=>({name,records:filtered.filter(d=>groupFor(text(d.fields["Design Category"]))===name)})).filter(g=>g.records.length);
 async function update(record:AirtableRow,fields:Record<string,unknown>,message:string){if(saving)return;setSaving(true);try{await api("PATCH",{table:"Design Board",id:record.id,fields});setNotice({kind:"success",text:message});setDetail(null);await load()}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Unable to update design"})}finally{setSaving(false)}}
 async function duplicate(record:AirtableRow){if(saving)return;setSaving(true);const allowed=["Design Title","Event","Design Category","Design File","Preview Image","Design Link","Version","Client Comments","Internal Notes","Visible to Client"];const fields=Object.fromEntries(allowed.filter(k=>record.fields[k]!==undefined).map(k=>[k,record.fields[k]]));fields["Design Title"]=`${text(record.fields["Design Title"])} - Version ${Number(record.fields.Version||1)+1}`;fields.Version=Number(record.fields.Version||1)+1;fields["Approval Status"]="Draft";fields["Approval Date"]=null;try{await api("POST",{table:"Design Board",requestId:requestId(),fields});setNotice({kind:"success",text:"New draft version created."});await load()}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Unable to duplicate design"})}finally{setSaving(false)}}
 async function remove(record:AirtableRow){if(!confirm(`Delete “${text(record.fields["Design Title"])}”? This cannot be undone.`))return;try{await api("DELETE",{table:"Design Board",id:record.id});setNotice({kind:"success",text:"Design deleted from Airtable."});setDetail(null);await load()}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Unable to delete design"})}}
 const visible=filtered.filter(d=>Boolean(d.fields["Visible to Client"]));
 if(clientMode)return <ClientPreview records={visible} eventName={eventName} onClose={()=>setClientMode(false)}/>;
 return <section className={embedded?"design-studio embedded":"design-studio"}><header className="design-studio-head"><div><p className="eyebrow">EVENTART CREATIVE WORKSPACE</p><h1>{embedded?"Design Studio":"Design Studio"}</h1><p>{embedded?`Creative direction for ${text(event?.fields["Event Name"])}`:"A visual portfolio of every EventArt celebration."}</p></div><div><button onClick={()=>setClientMode(true)}>Preview as Client</button><button className="gold-button" onClick={()=>setForm({})}>+ Add Design</button></div></header>{notice&&<div className={`workspace-message ${notice.kind}`}>{notice.text}</div>}
 <div className="design-filters"><input aria-label="Search designs" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search designs…"/>{!event&&<select aria-label="Filter by event" value={eventFilter} onChange={e=>setEventFilter(e.target.value)}><option value="All">All events</option>{events.map(e=><option key={e.id} value={e.id}>{text(e.fields["Event Name"])}</option>)}</select>}<select aria-label="Filter by category" value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{categories.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter by approval status" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Sort designs" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Most recent</option><option value="event">Event</option><option value="title">Title</option><option value="version">Version</option></select></div>
 {loading?<div className="design-empty">Loading the Design Studio…</div>:!filtered.length?<div className="design-empty"><img src="/eventart-logo-transparent.png" alt="EventArt"/><h2>No designs have been added yet.</h2><p>Upload your first design concept.</p><button className="gold-button" onClick={()=>setForm({})}>Add Design</button></div>:embedded?groups.map(g=><section className="design-group" key={g.name}><h2>{g.name}</h2><div className="design-gallery">{g.records.map(d=><DesignCard key={d.id} record={d} eventName={eventName(d)} onView={()=>setDetail(d)} onEdit={()=>setForm({record:d})} onDuplicate={()=>duplicate(d)} onDelete={()=>remove(d)} onOpenEvent={onOpenEvent?()=>{const e=events.find(e=>Array.isArray(d.fields.Event)&&d.fields.Event.includes(e.id));if(e)onOpenEvent(e)}:undefined}/>)}</div></section>):<div className="design-gallery">{filtered.map(d=><DesignCard key={d.id} record={d} eventName={eventName(d)} onView={()=>setDetail(d)} onEdit={()=>setForm({record:d})} onDuplicate={()=>duplicate(d)} onDelete={()=>remove(d)} onOpenEvent={onOpenEvent?()=>{const e=events.find(e=>Array.isArray(d.fields.Event)&&d.fields.Event.includes(e.id));if(e)onOpenEvent(e)}:undefined}/>)}</div>}
 {form&&<RecordForm table="Design Board" record={form.record} contextEvent={event?.id} onClose={()=>setForm(null)} onSaved={()=>{setForm(null);setNotice({kind:"success",text:form.record?"Design updated successfully.":"Design created successfully."});load()}}/>}{detail&&<DesignDetail record={detail} eventName={eventName(detail)} onClose={()=>setDetail(null)} onEdit={()=>{setForm({record:detail});setDetail(null)}} onStatus={(value)=>update(detail,{"Approval Status":value,"Approval Date":value==="Approved"||value==="Final"?new Date().toISOString().slice(0,10):null},`Design marked ${value}.`)}/>}</section>
}

function StatusBadge({value}:{value:unknown}){const status=text(value)||"Draft";return <span className={`design-status ${status.toLowerCase().replaceAll(" ","-")}`}>{status}</span>}
function DesignCard({record,eventName,onView,onEdit,onDuplicate,onDelete,onOpenEvent}:{record:AirtableRow;eventName:string;onView:()=>void;onEdit:()=>void;onDuplicate:()=>void;onDelete:()=>void;onOpenEvent?:()=>void}){const f=record.fields;const image=attachmentUrl(f["Preview Image"])||attachmentUrl(f["Design File"]);return <article className="design-card"><button className="design-image" onClick={onView}>{image?<img src={image} alt={text(f["Design Title"])}/>:<div><span>EA</span><small>Preview not yet added</small></div>}</button><div className="design-card-body"><div className="design-card-meta"><span>{text(f["Design Category"])||"Design Concept"}</span><StatusBadge value={f["Approval Status"]}/></div><h3>{text(f["Design Title"])}</h3><p>{eventName||"Event not linked"}</p><div className="design-version"><span>Version {text(f.Version)||"1"}</span><span>{text(f["Date Submitted"])}</span></div><div className="design-actions"><button onClick={onView}>View</button><button onClick={onEdit}>Edit</button><button onClick={onDuplicate}>Duplicate</button><button onClick={onDelete}>Delete</button>{onOpenEvent&&<button onClick={onOpenEvent}>Open Event</button>}{f["Design Link"]&&<a href={text(f["Design Link"])} target="_blank" rel="noreferrer">Open Link</a>}{attachmentUrl(f["Design File"])&&<a href={attachmentUrl(f["Design File"])} download>Download</a>}</div></div></article>}
function DesignDetail({record,eventName,onClose,onEdit,onStatus}:{record:AirtableRow;eventName:string;onClose:()=>void;onEdit:()=>void;onStatus:(s:string)=>void}){const f=record.fields;const image=attachmentUrl(f["Preview Image"])||attachmentUrl(f["Design File"]);return <div className="design-modal"><button className="design-modal-scrim" onClick={onClose}/><article><button className="design-close" onClick={onClose}>×</button>{image?<img className="design-detail-image" src={image} alt={text(f["Design Title"])}/>:<div className="design-detail-placeholder">Preview not yet added</div>}<div className="design-detail-content"><p className="eyebrow">{text(f["Design Category"])}</p><h2>{text(f["Design Title"])}</h2><StatusBadge value={f["Approval Status"]}/><dl>{[["Event",eventName],["Version",f.Version],["Date submitted",f["Date Submitted"]],["Approval date",f["Approval Date"]]].map(([k,v])=><div key={String(k)}><dt>{k}</dt><dd>{text(v)||"—"}</dd></div>)}</dl>{f["Client Comments"]&&<section><h3>Client Comments</h3><p>{text(f["Client Comments"])}</p></section>}<section className="internal-notes"><h3>Internal Notes</h3><p>{text(f["Internal Notes"])||"No internal notes."}</p></section><div className="detail-links">{f["Design Link"]&&<a href={text(f["Design Link"])} target="_blank" rel="noreferrer">Open Design Link</a>}{attachmentUrl(f["Design File"])&&<a href={attachmentUrl(f["Design File"])} download>Download Design File</a>}</div><div className="approval-actions"><button onClick={onEdit}>Edit</button><button onClick={()=>onStatus("Sent to Client")}>Send to Client</button><button onClick={()=>onStatus("Changes Requested")}>Request Changes</button><button onClick={()=>onStatus("Approved")}>Approve</button><button className="gold-button" onClick={()=>onStatus("Final")}>Mark Final</button></div></div></article></div>}
function ClientPreview({records,eventName,onClose}:{records:AirtableRow[];eventName:(r:AirtableRow)=>string;onClose:()=>void}){return <div className="client-design-preview"><header><img src="/eventart-logo-transparent.png" alt="EventArt"/><div><h1>Your Event Design</h1><p>Luxury Event Design & Styling</p></div><button onClick={onClose}>Close Preview</button></header>{records.length?<div className="client-design-grid">{records.map(r=>{const f=r.fields;const image=attachmentUrl(f["Preview Image"])||attachmentUrl(f["Design File"]);return <article key={r.id}>{image&&<img src={image} alt={text(f["Design Title"])}/>}<span>{text(f["Design Category"])}</span><h2>{text(f["Design Title"])}</h2><p>{eventName(r)} · Version {text(f.Version)||"1"}</p>{f["Client Comments"]&&<blockquote>{text(f["Client Comments"])}</blockquote>}<StatusBadge value={f["Approval Status"]}/><div>{f["Design Link"]&&<a href={text(f["Design Link"])} target="_blank" rel="noreferrer">View Design</a>}{attachmentUrl(f["Design File"])&&<a href={attachmentUrl(f["Design File"])} download>Download File</a>}</div></article>})}</div>:<div className="design-empty"><h2>No client-visible designs are currently available.</h2></div>}</div>}
