"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import BudgetWorkspace from "./BudgetWorkspace";
import RecordForm,{AirtableRow} from "./RecordForm";

type Props={event:AirtableRow;onBack:()=>void;initialTab?:string};
const tabs=["Overview","Budget & Proposal","Guests","Rental Orders","Payments","Timeline / Tasks","Vendors","Seating","Design Board","Notes"];
const sectionTable:Record<string,string>={Guests:"Guests","Rental Orders":"Rental Orders",Payments:"Payments","Timeline / Tasks":"Timeline",Vendors:"Vendors",Seating:"Seating Tables","Design Board":"Design Board"};
const columns:Record<string,string[]>={Guests:["Full Name","Email","RSVP Status","Assigned Table","Meal Choice","VIP"],"Rental Orders":["Order ID","Rental Item","Quantity","Rental Start Date","Rental End Date","Total Rental","Order Status"],Payments:["Payment ID","Payment Type","Payment Amount","Payment Date","Payment Status","Invoice Number"],Timeline:["Timeline Item","Date","Start Time","Category","Responsible Person","Status","Priority"],Vendors:["Vendor Name","Category","Contact Person","Contract Status","Total Fee","Balance Due"],"Seating Tables":["Table Name","Table Number","Table Type","Capacity","Assigned Guest Count","Remaining Seats"],"Design Board":["Design Title","Design Category","Version","Approval Status","Date Submitted","Visible to Client"]};
const show=(v:unknown)=>Array.isArray(v)?v.join(", "):typeof v==="boolean"?(v?"Yes":"No"):String(v??"—");

export default function EventWorkspace({event:initial,onBack,initialTab="Overview"}:Props){
 const [event,setEvent]=useState(initial);const [tab,setTab]=useState(initialTab);const [data,setData]=useState<Record<string,AirtableRow[]>>({});const [clients,setClients]=useState<AirtableRow[]>([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState("");const [form,setForm]=useState<{table:string;record?:AirtableRow|null}|null>(null);const [message,setMessage]=useState<{kind:"success"|"error";text:string}|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const tables=["Guests","Rental Orders","Payments","Timeline","Vendors","Seating Tables","Design Board","Clients"];const entries=await Promise.all(tables.map(async table=>{const r=await fetch(`/api/airtable?table=${encodeURIComponent(table)}&pageSize=100`);const d=await r.json();if(!r.ok)throw new Error(typeof d.error==="string"?d.error:d.error?.message||`Unable to load ${table}`);return [table,d.records||[]] as const}));const all=Object.fromEntries(entries);setClients(all.Clients);delete all.Clients;setData(all)}catch(e){setMessage({kind:"error",text:e instanceof Error?e.message:"Unable to load workspace"})}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const clientName=clients.filter(c=>Array.isArray(event.fields.Clients)&&event.fields.Clients.includes(c.id)).map(c=>show(c.fields["Client Name"])).join(", ")||"—";
 const related=(table:string)=>(data[table]||[]).filter(r=>Array.isArray(r.fields.Event)&&r.fields.Event.includes(event.id));
 const overview=["Event Name","Event Type","Ceremony Date & Time","Venue Name","Venue Address","Guest Count","Theme","Color Palette","Budget","Total Contract","Deposit Paid","Event Status","Lead Planner"];
 function saved(row:AirtableRow){if(form?.table==="Events")setEvent(row);setMessage({kind:"success",text:`${form?.record?"Changes saved":"Record created"} successfully.`});setForm(null);load()}
 if(tab==="Budget & Proposal")return <div className="event-workspace"><WorkspaceHeader event={event} client={clientName} onBack={onBack}/><WorkspaceTabs active={tab} setActive={setTab}/><BudgetWorkspace event={event} onBack={()=>setTab("Overview")}/></div>;
 const table=sectionTable[tab];const records=table?related(table):[];const filtered=records.filter(r=>JSON.stringify(r.fields).toLowerCase().includes(search.toLowerCase()));
 return <div className="event-workspace"><WorkspaceHeader event={event} client={clientName} onBack={onBack}/><WorkspaceTabs active={tab} setActive={t=>{setTab(t);setSearch("")}}/>{message&&<div className={`workspace-message ${message.kind}`}>{message.text}</div>}
   {tab==="Overview"?<section className="workspace-panel"><div className="workspace-section-head"><div><p className="eyebrow">EVENT OVERVIEW</p><h2>Event details</h2></div><button className="gold-button" onClick={()=>setForm({table:"Events",record:event})}>Edit Event</button></div><div className="overview-grid"><Info label="Client" value={clientName}/>{overview.map(name=><Info key={name} label={name==="Ceremony Date & Time"?"Event Date & Ceremony Time":name} value={event.fields[name]}/>) }<Info label="Event Priority" value="Unavailable in the current Airtable schema" muted/><Info label="Notes" value="Unavailable in the current Events table" muted/></div></section>
   :tab==="Notes"?<NotesPanel data={Object.values(data).flat().filter(r=>Array.isArray(r.fields.Event)&&r.fields.Event.includes(event.id)&&r.fields.Notes)}/>
   :<section className="workspace-panel"><div className="workspace-section-head"><div><p className="eyebrow">LINKED AIRTABLE RECORDS</p><h2>{tab}</h2></div><div className="workspace-tools"><input aria-label={`Search ${tab}`} value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${tab.toLowerCase()}…`}/><button className="gold-button" onClick={()=>setForm({table})}>+ Add</button></div></div>{loading?<div className="workspace-empty">Loading…</div>:<RelatedTable table={table} rows={filtered} onEdit={record=>setForm({table,record})}/>}</section>}
   {form&&<RecordForm table={form.table} record={form.record} contextEvent={event.id} contextClient={Array.isArray(event.fields.Clients)?String(event.fields.Clients[0]||""):""} onClose={()=>setForm(null)} onSaved={saved}/>}</div>
}

function WorkspaceHeader({event,client,onBack}:{event:AirtableRow;client:string;onBack:()=>void}){return <div className="workspace-event-head"><div><button className="back-link" onClick={onBack}>← All Events</button><p className="eyebrow">EVENT WORKSPACE</p><h1>{show(event.fields["Event Name"])}</h1><p>{client} · {event.fields["Ceremony Date & Time"]?new Date(String(event.fields["Ceremony Date & Time"])).toLocaleDateString("en-CA"):"Date TBD"} · {show(event.fields["Venue Name"])}</p></div><span className="pill">{show(event.fields["Event Status"])}</span></div>}
function WorkspaceTabs({active,setActive}:{active:string;setActive:(v:string)=>void}){return <nav className="workspace-tabs" aria-label="Event sections">{tabs.map(t=><button key={t} className={active===t?"active":""} onClick={()=>setActive(t)}>{t}</button>)}</nav>}
function Info({label,value,muted}:{label:string;value:unknown;muted?:boolean}){return <div className={muted?"overview-item muted-field":"overview-item"}><span>{label}</span><b>{show(value)}</b></div>}
function RelatedTable({table,rows,onEdit}:{table:string;rows:AirtableRow[];onEdit:(r:AirtableRow)=>void}){const fields=columns[table]||[];if(!rows.length)return <div className="workspace-empty"><div>EA</div><h3>No linked records yet</h3><p>Use Add to create the first record for this event.</p></div>;return <div className="table-wrap"><table><thead><tr>{fields.map(f=><th key={f}>{f}</th>)}<th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{fields.map(f=><td key={f}>{show(r.fields[f])}</td>)}<td><button className="edit" onClick={()=>onEdit(r)}>Edit</button></td></tr>)}</tbody></table></div>}
function NotesPanel({data}:{data:AirtableRow[]}){return <section className="workspace-panel"><div className="workspace-section-head"><div><p className="eyebrow">LINKED NOTES</p><h2>Notes</h2></div></div>{data.length?<div className="notes-grid">{data.map(r=><article key={r.id}><b>{show(r.fields["Timeline Item"]||r.fields["Vendor Name"]||r.fields["First Name"]||r.fields["Order ID"]||"Linked record")}</b><p>{show(r.fields.Notes)}</p></article>)}</div>:<div className="workspace-empty"><h3>No linked notes</h3><p>The Events table has no Notes field. Notes entered on linked records will appear here.</p></div>}</section>}
