"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import BudgetWorkspace from "./BudgetWorkspace";
import RecordForm,{AirtableRow} from "./RecordForm";
import DesignStudio from "./DesignStudio";
import FilesMedia from "./FilesMedia";
import FindMySeatQR from "./FindMySeatQR";
import CanvaSeatingDesign from "./CanvaSeatingDesign";
import SeatingAssignments from "./SeatingAssignments";

type Props={event:AirtableRow;onBack:()=>void;initialTab?:string;role?:"owner"|"team"|"client"};
const tabs=["Overview","Budget & Proposal","Guests","Rental Orders","Payments","Timeline / Tasks","Vendors","Seating","Design Studio","Files & Media","Notes"];
const teamTabs=new Set(["Overview","Guests","Timeline / Tasks","Vendors","Seating","Design Studio","Files & Media","Notes"]);
const sectionTable:Record<string,string>={Guests:"Guests","Rental Orders":"Rental Orders",Payments:"Payments","Timeline / Tasks":"Timeline",Vendors:"Vendors",Seating:"Seating Tables","Design Board":"Design Board"};
const columns:Record<string,string[]>={Guests:["Full Name","Email","RSVP Status","Seating Chart","Meal Choice","VIP"],"Rental Orders":["Order ID","Rental Item","Quantity","Rental Start Date","Rental End Date","Total Rental","Order Status"],Payments:["Payment ID","Payment Type","Payment Amount","Payment Date","Payment Status","Invoice Number"],Timeline:["Timeline Item","Date","Start Time","Category","Responsible Person","Status","Priority"],Vendors:["Vendor Name","Category","Contact Person","Contract Status","Total Fee","Balance Due"],"Seating Tables":["Table Name","Table Number","Table Type","Capacity","Assigned Guest Count","Remaining Seats"],"Design Board":["Design Title","Design Category","Version","Approval Status","Date Submitted","Visible to Client"]};
const columnLabel=(table:string,field:string)=>table==="Guests"&&field==="Seating Chart"?"Assigned Table":field;
const guestDisplayName=(row:AirtableRow)=>{const parts=[row.fields["First Name"],row.fields["Last Name"]].map(value=>String(value||"").trim()).filter(Boolean);return String(parts.length?parts.join(" "):row.fields["Full Name"]||"Guest").replace(/\s+/g," ").trim()};
const show=(v:unknown)=>Array.isArray(v)?v.join(", "):typeof v==="boolean"?(v?"Yes":"No"):String(v??"—").replaceAll("_"," ").replace(/\s+/g," ").trim();
const currency=(v:unknown)=>new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v)||0);
const localDateTime=(v:unknown)=>{if(!v)return "—";const date=new Date(String(v));return Number.isNaN(date.getTime())?"—":new Intl.DateTimeFormat("en-CA",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Toronto"}).format(date)};
const recordValue=(record:AirtableRow,field:string)=>record.displayFields?.[field]||(["Start Time","End Time"].includes(field)?localDateTime(record.fields[field]):show(record.fields[field]));

export default function EventWorkspace({event:initial,onBack,initialTab="Overview",role="owner"}:Props){
 const [event,setEvent]=useState(initial);const [tab,setTab]=useState(initialTab);const [data,setData]=useState<Record<string,AirtableRow[]>>({});const [clients,setClients]=useState<AirtableRow[]>([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState("");const [form,setForm]=useState<{table:string;record?:AirtableRow|null}|null>(null);const [message,setMessage]=useState<{kind:"success"|"error";text:string}|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const tables=role==="team"?["Events","Guests","Timeline","Vendors","Seating Tables","Design Board"]:["Events","Guests","Rental Orders","Payments","Timeline","Vendors","Seating Tables","Design Board","Budgets","Clients"];const entries=await Promise.all(tables.map(async table=>{const r=await fetch(`/api/airtable?table=${encodeURIComponent(table)}&pageSize=100&resolveLinks=1${table==="Events"&&role==="owner"?"&financialSummary=1":""}`);const d=await r.json();if(!r.ok)throw new Error(typeof d.error==="string"?d.error:d.error?.message||`Unable to load ${table}`);return [table,d.records||[]] as const}));const all=Object.fromEntries(entries);setClients(all.Clients||[]);const refreshedEvent=(all.Events||[]).find((row:AirtableRow)=>row.id===initial.id);if(refreshedEvent)setEvent(refreshedEvent);delete all.Clients;delete all.Events;setData(all)}catch(e){setMessage({kind:"error",text:e instanceof Error?e.message:"Unable to load workspace"})}finally{setLoading(false)}},[initial.id,role]);
 useEffect(()=>{load()},[load]);
 const clientName=clients.filter(c=>Array.isArray(event.fields.Clients)&&event.fields.Clients.includes(c.id)).map(c=>show(c.fields["Client Name"])).join(", ")||"—";
 const related=(table:string)=>(data[table]||[]).filter(r=>Array.isArray(r.fields.Event)&&r.fields.Event.includes(event.id));
 const totalContract=Number(event.computedFields?.["Total Contract"]||0);
 const depositPaid=Number(event.computedFields?.["Amount Paid"]||0);
 const remainingBalance=Math.max(0,Number(event.computedFields?.["Balance Due"]||0));
 const overview=["Event Name","Event Type","Venue Name","Venue Address","Guest Count","Theme","Color Palette","Event Status","Lead Planner"];
 function saved(row:AirtableRow){if(form?.table==="Events")setEvent(row);if(form?.table==="Guests"&&!form.record){const name=guestDisplayName(row);const seatingId=Array.isArray(row.fields["Seating Chart"])?String(row.fields["Seating Chart"][0]||""):"";const target=(data["Seating Tables"]||[]).find(table=>table.id===seatingId);setMessage({kind:"success",text:target?`${name} was added to ${String(target.fields["Table Name"]||"the selected table")}.`:`${name} was added to Unassigned Guests.`});setTab("Seating")}else setMessage({kind:"success",text:`${form?.record?"Changes saved":"Record created"} successfully.`});setForm(null);load()}
 async function remove(table:string,row:AirtableRow){const label=String(row.fields[columns[table]?.[0]]||"this record");if(!window.confirm(`Delete “${label}”? This cannot be undone.`))return;try{const r=await fetch("/api/airtable",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({table,id:row.id})});const d=await r.json();if(!r.ok)throw new Error(typeof d.error==="string"?d.error:d.error?.message||"Unable to delete record");setMessage({kind:"success",text:"Record deleted from Airtable."});await load()}catch(e){setMessage({kind:"error",text:e instanceof Error?e.message:"Unable to delete record"})}}
 if(tab==="Budget & Proposal")return <div className="event-workspace"><WorkspaceHeader event={event} client={clientName} onBack={onBack}/><WorkspaceTabs active={tab} setActive={setTab} role={role}/><BudgetWorkspace event={event} onBack={()=>setTab("Overview")}/></div>;
 if(tab==="Design Studio")return <div className="event-workspace"><WorkspaceHeader event={event} client={clientName} onBack={onBack}/><WorkspaceTabs active={tab} setActive={setTab} role={role}/><DesignStudio event={event} embedded/></div>;
 if(tab==="Files & Media")return <div className="event-workspace"><WorkspaceHeader event={event} client={clientName} onBack={onBack}/><WorkspaceTabs active={tab} setActive={setTab} role={role}/><FilesMedia event={event} role={role}/></div>;
 const table=sectionTable[tab];const records=table?related(table):[];const filtered=records.filter(r=>JSON.stringify(r.fields).toLowerCase().includes(search.toLowerCase()));
 return <div className="event-workspace"><WorkspaceHeader event={event} client={clientName} onBack={onBack}/><WorkspaceTabs active={tab} setActive={t=>{setTab(t);setSearch("")}} role={role}/>{message&&<div className={`workspace-message ${message.kind}`}>{message.text}</div>}
   {tab==="Overview"?<section className="workspace-panel"><div className="workspace-section-head"><div><p className="eyebrow">EVENT OVERVIEW</p><h2>Event details</h2></div><button className="gold-button" onClick={()=>setForm({table:"Events",record:event})}>Edit Event</button></div><div className="overview-grid"><Info label="Client" value={clientName}/><Info label="Ceremony Time" value={localDateTime(event.fields["Ceremony Date & Time"])}/>{overview.map(name=><Info key={name} label={name} value={event.fields[name]}/>) }<Info label="Budget" value={event.fields.Budget==null?"—":currency(event.fields.Budget)}/><Info label="Total Contract" value={currency(totalContract)}/><Info label="Deposit Paid" value={currency(depositPaid)}/><Info label="Remaining Balance" value={currency(remainingBalance)}/><Info label="Event Priority" value="—" muted/><Info label="Notes" value="—" muted/></div></section>
   :tab==="Notes"?<NotesPanel data={Object.values(data).flat().filter(r=>Array.isArray(r.fields.Event)&&r.fields.Event.includes(event.id)&&r.fields.Notes)}/>
   :<section className="workspace-panel">{tab==="Seating"?<><FindMySeatQR event={event} onChanged={load}/><CanvaSeatingDesign event={event} onChanged={load}/><div className="workspace-section-head"><div><p className="eyebrow">LIVE GUEST ASSIGNMENTS</p><h2>Seating Tables & Guests</h2></div><div className="workspace-tools"><input aria-label="Search Seating" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tables or guests…"/><button onClick={()=>setForm({table:"Guests"})}>+ Add Guest</button><button className="gold-button" onClick={()=>setForm({table:"Seating Tables"})}>+ Add Table</button></div></div>{loading?<div className="workspace-empty">Loading…</div>:<SeatingAssignments eventId={event.id} tables={related("Seating Tables")} guests={related("Guests")} search={search} onChanged={load} onEditGuest={record=>setForm({table:"Guests",record})} onEditTable={record=>setForm({table:"Seating Tables",record})} onDeleteTable={record=>remove("Seating Tables",record)}/>}</>:<><div className="workspace-section-head"><div><p className="eyebrow">LINKED AIRTABLE RECORDS</p><h2>{tab}</h2></div><div className="workspace-tools"><input aria-label={`Search ${tab}`} value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${tab.toLowerCase()}…`}/><button className="gold-button" onClick={()=>setForm({table})}>+ Add</button></div></div>{loading?<div className="workspace-empty">Loading…</div>:<RelatedTable table={table} rows={filtered} onEdit={record=>setForm({table,record})} onDelete={record=>remove(table,record)}/>}</>}</section>}
   {form&&<RecordForm table={form.table} record={form.record} contextEvent={event.id} contextClient={Array.isArray(event.fields.Clients)?String(event.fields.Clients[0]||""):""} onClose={()=>setForm(null)} onSaved={saved}/>}</div>
}

function WorkspaceHeader({event,client,onBack}:{event:AirtableRow;client:string;onBack:()=>void}){return <div className="workspace-event-head"><div><button className="back-link" onClick={onBack}>← All Events</button><p className="eyebrow">EVENT WORKSPACE</p><h1>{show(event.fields["Event Name"])}</h1><p>{client} · {event.fields["Ceremony Date & Time"]?new Date(String(event.fields["Ceremony Date & Time"])).toLocaleDateString("en-CA"):"Date TBD"} · {show(event.fields["Venue Name"])}</p></div><span className="pill">{show(event.fields["Event Status"])}</span></div>}
function WorkspaceTabs({active,setActive,role="owner"}:{active:string;setActive:(v:string)=>void;role?:"owner"|"team"|"client"}){const visible=role==="team"?tabs.filter(tab=>teamTabs.has(tab)):tabs;return <nav className="workspace-tabs" aria-label="Event sections">{visible.map(t=><button key={t} className={active===t?"active":""} onClick={()=>setActive(t)}>{t}</button>)}</nav>}
function Info({label,value,muted}:{label:string;value:unknown;muted?:boolean}){return <div className={muted?"overview-item muted-field":"overview-item"}><span>{label}</span><b>{show(value)}</b></div>}
function RelatedTable({table,rows,onEdit,onDelete}:{table:string;rows:AirtableRow[];onEdit:(r:AirtableRow)=>void;onDelete:(r:AirtableRow)=>void}){const fields=columns[table]||[];if(!rows.length)return <div className="workspace-empty"><div>EA</div><h3>No linked records yet</h3><p>Use Add to create the first record for this event.</p></div>;return <div className="table-wrap"><table><thead><tr>{fields.map(f=><th key={f}>{columnLabel(table,f)}</th>)}<th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{fields.map(f=><td key={f}>{table==="Guests"&&f==="Full Name"?guestDisplayName(r):recordValue(r,f)}</td>)}<td><button className="edit" onClick={()=>onEdit(r)}>Edit</button><button className="danger" onClick={()=>onDelete(r)}>Delete</button></td></tr>)}</tbody></table></div>}
function NotesPanel({data}:{data:AirtableRow[]}){return <section className="workspace-panel"><div className="workspace-section-head"><div><p className="eyebrow">LINKED NOTES</p><h2>Notes</h2></div></div>{data.length?<div className="notes-grid">{data.map(r=><article key={r.id}><b>{show(r.fields["Timeline Item"]||r.fields["Vendor Name"]||r.fields["First Name"]||r.fields["Order ID"]||"Linked record")}</b><p>{show(r.fields.Notes)}</p></article>)}</div>:<div className="workspace-empty"><h3>No linked notes</h3><p>The Events table has no Notes field. Notes entered on linked records will appear here.</p></div>}</section>}

type QRFile={id?:string;filename?:string;url?:string;type?:string};
function SeatingQRCard({event,onChanged}:{event:AirtableRow;onChanged:()=>Promise<void>}){
 const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const qr=(Array.isArray(event.fields["Seating QR Code"])?event.fields["Seating QR Code"]:[]) as QRFile[];const current=qr[0];
 async function clear(){const response=await fetch("/api/airtable",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({table:"Events",id:event.id,fields:{"Seating QR Code":[]}})});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==="string"?data.error:data.error?.message||"Unable to remove QR code")}
 async function upload(file:File){const extension=file.name.split(".").pop()?.toLowerCase();if(!["jpg","jpeg","png","webp"].includes(extension||"")){setNotice("Choose a JPG, PNG, or WEBP QR-code image.");return}if(file.size>5*1024*1024){setNotice("The QR-code image must be 5 MB or smaller.");return}if(current&&!window.confirm("Replace the existing Seating QR Code?"))return;setBusy(true);setNotice("");try{if(current)await clear();const form=new FormData();form.set("table","Events");form.set("record",event.id);form.set("attachmentField","Seating QR Code");form.append("files",file);const response=await fetch("/api/airtable/upload",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(typeof data.error==="string"?data.error:data.error?.message||"Unable to upload QR code");await onChanged();setNotice("Seating QR Code saved to Airtable.")}catch(error){setNotice(error instanceof Error?error.message:"Unable to upload QR code")}finally{setBusy(false);if(input.current)input.current.value=""}}
 async function remove(){if(!current||!window.confirm("Remove the Seating QR Code from this event?"))return;setBusy(true);setNotice("");try{await clear();await onChanged();setNotice("Seating QR Code removed.")}catch(error){setNotice(error instanceof Error?error.message:"Unable to remove QR code")}finally{setBusy(false)}}
 function print(){if(!current?.url)return;const popup=window.open("","_blank","width=720,height=820");if(!popup){setNotice("Allow pop-ups to print the QR-code card.");return}const name=String(event.fields["Event Name"]||"Event").replace(/[<>&]/g,"");const date=event.fields["Ceremony Date & Time"]?new Date(String(event.fields["Ceremony Date & Time"])).toLocaleDateString("en-CA",{dateStyle:"long"}):"";popup.document.write(`<!doctype html><html><head><title>${name} Seating QR Code</title><style>body{font-family:Arial;text-align:center;padding:48px;color:#111}.card{border:1px solid #c9a858;padding:42px;max-width:480px;margin:auto}img.logo{width:150px;height:90px;object-fit:contain}img.qr{width:300px;height:300px;object-fit:contain;margin:25px auto}h1{font-family:Georgia;font-weight:400}p{color:#777}@media print{button{display:none}}</style></head><body><div class="card"><img class="logo" src="${location.origin}/eventart-logo-transparent.png"><h1>${name}</h1><h2>Scan to Find Your Seat</h2><img class="qr" src="${current.url}"><p>${date}</p></div><button onclick="window.print()">Print</button></body></html>`);popup.document.close()}
 return <section className="seating-qr-card"><div className="seating-qr-copy"><p className="eyebrow">EVENT SEATING QR CODE</p><h2>Scan to Find Your Seat</h2><p>{show(event.fields["Event Name"])}</p>{notice&&<span className="qr-notice">{notice}</span>}<div className="qr-actions"><button className="gold-button" disabled={busy} onClick={()=>input.current?.click()}>{busy?"Saving…":current?"Replace QR Code":"Upload QR Code"}</button>{current?.url&&<><a href={current.url} download={current.filename||"EventArt-Seating-QR"}>Download QR Code</a><button onClick={print}>Print QR Code</button><button className="danger" disabled={busy} onClick={remove}>Remove</button></>}</div><input ref={input} className="qr-file-input" type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)upload(file)}}/></div><div className="qr-preview">{current?.url?<img src={current.url} alt={`Seating QR Code for ${show(event.fields["Event Name"])}`}/>:<div><b>EA</b><span>No QR code uploaded</span></div>}</div></section>
}
