"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import RecordForm,{AirtableRow} from "./RecordForm";
type FileItem={id:string;record:AirtableRow;table:string;field:string;name:string;url:string;type:string;size:number;group:string};
const isLinked=(v:unknown,id:string)=>Array.isArray(v)&&v.includes(id);
const attachments=(v:unknown)=>Array.isArray(v)?v.filter(x=>x&&typeof x==="object") as Array<{id?:string;filename?:string;url?:string;type?:string;size?:number}>:[];
async function request(method:string,body?:unknown,query=""){const r=await fetch(`/api/airtable${query?`?${query}`:""}`,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(typeof d.error==="string"?d.error:d.error?.message||"Unable to complete this action");return d}
export default function FilesMedia({event}:{event:AirtableRow}){const [files,setFiles]=useState<FileItem[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[type,setType]=useState("All"),[form,setForm]=useState(false),[notice,setNotice]=useState<{kind:"success"|"error";text:string}|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const [designs,vendors,budgets]=await Promise.all([request("GET",undefined,"table=Design%20Board&pageSize=100"),request("GET",undefined,"table=Vendors&pageSize=100"),request("GET",undefined,"table=Budgets&pageSize=100")]);const list:FileItem[]=[];const add=(record:AirtableRow,table:string,field:string,group:string)=>attachments(record.fields[field]).forEach((a,i)=>a.url&&list.push({id:a.id||`${record.id}-${field}-${i}`,record,table,field,name:a.filename||"Attachment",url:a.url,type:a.type||"application/octet-stream",size:a.size||0,group}));(designs.records as AirtableRow[]).filter(r=>isLinked(r.fields.Event,event.id)).forEach(r=>{add(r,"Design Board","Preview Image","Images");add(r,"Design Board","Design File",String(r.fields["Design Category"]).includes("Floor Plan")?"Floor Plans":String(r.fields["Design Category"]).includes("Sign")?"Signage":"Design Files")});(vendors.records as AirtableRow[]).filter(r=>isLinked(r.fields.Event,event.id)).forEach(r=>add(r,"Vendors","Contract","Vendor Documents"));(budgets.records as AirtableRow[]).filter(r=>isLinked(r.fields.Event,event.id)).forEach(r=>add(r,"Budgets","Proposal PDF","Contracts"));setFiles(list)}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Unable to load files"})}finally{setLoading(false)}},[event.id]);useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>files.filter(f=>f.name.toLowerCase().includes(query.toLowerCase())).filter(f=>type==="All"||type==="Images"?type==="All"||f.type.startsWith("image/"):type==="PDF"?f.type.includes("pdf"):!f.type.startsWith("image/")&&!f.type.includes("pdf")),[files,query,type]);const groups=["Design Files","Images","Floor Plans","Contracts","Vendor Documents","Signage","Other"].map(name=>({name,items:filtered.filter(f=>f.group===name)})).filter(g=>g.items.length);
 async function remove(file:FileItem){if(!confirm(`Remove “${file.name}”? Other attachments will remain.`))return;const retained=attachments(file.record.fields[file.field]).filter(a=>a.id!==file.id).map(a=>({id:a.id}));try{await request("PATCH",{table:file.table,id:file.record.id,fields:{[file.field]:retained}});setNotice({kind:"success",text:"Attachment removed. Other files were preserved."});await load()}catch(e){setNotice({kind:"error",text:e instanceof Error?e.message:"Unable to remove attachment"})}}
 return <section className="files-media"><header><div><p className="eyebrow">EVENT FILE LIBRARY</p><h2>Files & Media</h2><p>Design files, images and documents connected to this event.</p></div><button className="gold-button" onClick={()=>setForm(true)}>+ Upload Files</button></header>{notice&&<div className={`workspace-message ${notice.kind}`}>{notice.text}</div>}<div className="file-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by filename…"/><select value={type} onChange={e=>setType(e.target.value)}><option>All</option><option>Images</option><option>PDF</option><option>Documents</option></select></div>{loading?<div className="workspace-empty">Loading files…</div>:!filtered.length?<div className="workspace-empty"><h3>No files have been added yet.</h3><p>Upload files through a Design Board record for this event.</p></div>:groups.map(group=><section className="file-group" key={group.name}><h3>{group.name}</h3><div className="file-grid">{group.items.map(file=><article key={file.id}>{file.type.startsWith("image/")?<img src={file.url} alt={file.name}/>:<div className="file-icon">{file.type.includes("pdf")?"PDF":"FILE"}</div>}<div><b>{file.name}</b><span>{file.type} {file.size?`· ${(file.size/1048576).toFixed(1)} MB`:""}</span><p><a href={file.url} target="_blank" rel="noreferrer">Open</a><a href={file.url} download>Download</a><button onClick={()=>remove(file)}>Remove</button></p></div></article>)}</div></section>)}{form&&<RecordForm table="Design Board" contextEvent={event.id} onClose={()=>setForm(false)} onSaved={()=>{setForm(false);setNotice({kind:"success",text:"Files uploaded and linked to this event."});load()}}/>}</section>}
