"use client";

import { useEffect, useMemo, useState } from "react";

export type AirtableRow={id:string;fields:Record<string,unknown>};
type Field={name:string;label?:string;type?:"text"|"email"|"tel"|"number"|"date"|"datetime-local"|"textarea"|"checkbox"|"select"|"multi"|"link"|"attachment";required?:boolean;options?:string[];linkTable?:string};

const choices={
 clientType:["Wedding","Birthday","Corporate","Baby Shower","Rental Only","Private Party"],clientStatus:["Inquiry","Consultation Booked","Proposal Sent","Booked","Completed","Lost"],
 eventType:["Wedding","Birthday","Baby Shower","Corporate","Anniversary","Rental Only","Proposal","Bridal Shower","Private Party"],eventStatus:["Inquiry","Consultation Scheduled","Proposal Sent","Contract Signed","Deposit Paid","Planning","Design Approved","Event Day","Event Completed","Cancelled","Archived"],colors:["White","Gold","Terracotta","Sage","Black","Brown","Red"],
 paymentType:["Booking Deposit","Progress Payment","Final Payment","Rental Deposit","Rental Balance","Refund","Damage Charge","Other","Design Deposit"],paymentMethod:["Cash","Debit","Credit Card","E-Transfer","Bank Transfer","Cheque"],paymentStatus:["Pending","Paid","Refunded","Partially Paid","Overdue","Cancelled"],
 orderStatus:["Inquiry","Reserved","Out for Delivery","Delivered","Picked Up","Returned","Cancelled"],rsvp:["Invited","Confirmed","Declined","Maybe","No Response"],meal:["Beef","Chicken","Fish","Vegetarian","Vegan","Kids Meal"],
 timelineCategory:["Planning","Delivery","Setup","Ceremony","Cocktail Hour","Reception","Vendor Arrival","Teardown","Pickup","Client Appointment","Payment Deadline"],timelineStatus:["Not Started","Confirmed","In Progress","Completed","Delayed","Cancelled"],priority:["High","Medium","Low"],
 vendorCategory:["Venue","Caterer","DJ","Photographer","Videographer","Florist","Cake","Officiant","Makeup Artist","Hair Stylist","Transportation","Security","Bartender","Rental Supplier","Entertainment","Other"],contractStatus:["Inquiry","Quote Received","Pending Approval","Booked","Deposit Paid","Paid in Full","Cancelled"],
 tableType:["Round","Rectangle","King Table","Sweetheart Table","Family Table","Kids Table","Vendor Table","Cocktail Table","Buffet Table","Other"],designCategory:["Mood Board","Ceremony Design","Reception Design","Floor Plan","SketchUp Mockup","AI Rendering","Welcome Sign","Seating Chart Sign","Menu","Table Design","Floral Design","Rental Selection","Thank You Gift","Other"],approval:["Draft","Internal Review","Sent to Client","Changes Requested","Approved","Final"]
};

export const formConfigs:Record<string,{title:string;fields:Field[]}>= {
 Clients:{title:"New Client",fields:[{name:"Client Name",required:true},{name:"Email",type:"email",required:true},{name:"Phone number",label:"Phone",type:"tel"},{name:"Client Type",type:"select",options:choices.clientType,required:true},{name:"Status",type:"select",options:choices.clientStatus,required:true},{name:"Notes",type:"textarea"}]},
 Events:{title:"New Event",fields:[{name:"Event Name",required:true},{name:"Clients",label:"Client",type:"link",linkTable:"Clients",required:true},{name:"Event Type",type:"select",options:choices.eventType,required:true},{name:"Ceremony Date & Time",label:"Event Date & Ceremony Time",type:"datetime-local",required:true},{name:"Venue Name"},{name:"Venue Address",type:"textarea"},{name:"Guest Count",type:"number"},{name:"Theme"},{name:"Color Palette",type:"multi",options:choices.colors},{name:"Budget",type:"number"},{name:"Event Status",type:"select",options:choices.eventStatus,required:true},{name:"Lead Planner",type:"select",options:["Maritza Paultre"]}]},
 Payments:{title:"New Payment",fields:[{name:"Event",type:"link",linkTable:"Events",required:true},{name:"Client",type:"link",linkTable:"Clients",required:true},{name:"Payment Type",type:"select",options:choices.paymentType,required:true},{name:"Payment Amount",type:"number",required:true},{name:"Payment Date",type:"date",required:true},{name:"Due Date",type:"date"},{name:"Payment Method",type:"select",options:choices.paymentMethod},{name:"Payment Status",type:"select",options:choices.paymentStatus,required:true},{name:"Invoice Number",label:"Invoice / Reference Number"},{name:"Notes",type:"textarea"}]},
 "Rental Orders":{title:"New Rental Order",fields:[{name:"Event",type:"link",linkTable:"Events",required:true},{name:"Client",type:"link",linkTable:"Clients",required:true},{name:"Rental Item",type:"link",linkTable:"Inventory",required:true},{name:"Quantity",type:"number",required:true},{name:"Rental Start Date",type:"date",required:true},{name:"Rental End Date",type:"date",required:true},{name:"Rental Price",type:"number"},{name:"Delivery Fee",type:"number"},{name:"Pickup Fee",type:"number"},{name:"Setup Fee",type:"number"},{name:"Security Deposit",type:"number"},{name:"Discount",type:"number"},{name:"Order Status",type:"select",options:choices.orderStatus,required:true},{name:"Notes",type:"textarea"}]},
 Guests:{title:"New Guest",fields:[{name:"Event",type:"link",linkTable:"Events",required:true},{name:"First Name",required:true},{name:"Last Name",required:true},{name:"Email",type:"email"},{name:"Phone",type:"tel"},{name:"RSVP Status",type:"select",options:choices.rsvp},{name:"Meal Choice",type:"select",options:choices.meal},{name:"Dietary Restrictions",type:"textarea"},{name:"Assigned Table"},{name:"Seat Number",type:"number"},{name:"VIP",type:"checkbox"},{name:"Notes",type:"textarea"}]},
 Timeline:{title:"New Timeline / Task Item",fields:[{name:"Timeline Item",required:true},{name:"Event",type:"link",linkTable:"Events",required:true},{name:"Date",type:"date",required:true},{name:"Start Time",type:"datetime-local"},{name:"End Time",type:"datetime-local"},{name:"Category",type:"select",options:choices.timelineCategory},{name:"Responsible Person"},{name:"Vendor"},{name:"Location"},{name:"Status",type:"select",options:choices.timelineStatus,required:true},{name:"Priority",type:"select",options:choices.priority},{name:"Notes",type:"textarea"}]},
 Vendors:{title:"New Vendor",fields:[{name:"Vendor Name",required:true},{name:"Category",type:"select",options:choices.vendorCategory,required:true},{name:"Contact Person"},{name:"Email",type:"email"},{name:"Phone",type:"tel"},{name:"Website"},{name:"Event",type:"link",linkTable:"Events",required:true},{name:"Contract Status",type:"select",options:choices.contractStatus},{name:"Arrival Time",type:"datetime-local"},{name:"Service Start Time",type:"datetime-local"},{name:"Service End Time",type:"datetime-local"},{name:"Total Fee",type:"number"},{name:"Amount Paid",type:"number"},{name:"Insurance Received",type:"checkbox"},{name:"Notes",type:"textarea"}]},
 "Seating Tables":{title:"New Seating Table",fields:[{name:"Table Name",required:true},{name:"Event",type:"link",linkTable:"Events",required:true},{name:"Table Number",type:"number"},{name:"Table Type",type:"select",options:choices.tableType},{name:"Capacity",type:"number",required:true},{name:"Table Location"},{name:"VIP Table",type:"checkbox"},{name:"Notes",type:"textarea"}]},
 "Design Board":{title:"New Design Record",fields:[{name:"Design Title",required:true},{name:"Event",type:"link",linkTable:"Events",required:true},{name:"Design Category",type:"select",options:choices.designCategory},{name:"Design File",type:"attachment"},{name:"Preview Image",type:"attachment"},{name:"Design Link"},{name:"Version",type:"number"},{name:"Approval Status",type:"select",options:choices.approval},{name:"Date Submitted",type:"date"},{name:"Client Comments",type:"textarea"},{name:"Internal Notes",type:"textarea"},{name:"Visible to Client",type:"checkbox"}]}
};

const labels:Record<string,string>={Clients:"Client Name",Events:"Event Name",Inventory:"Item Name","Seating Tables":"Table Name"};
const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;
function val(v:unknown){return Array.isArray(v)?v[0]||"":String(v??"")}

export default function RecordForm({table,record,contextEvent,contextClient,onClose,onSaved}:{table:string;record?:AirtableRow|null;contextEvent?:string;contextClient?:string;onClose:()=>void;onSaved:(r:AirtableRow)=>void}){
 const config=formConfigs[table];const [values,setValues]=useState<Record<string,unknown>>({});const [lookups,setLookups]=useState<Record<string,AirtableRow[]>>({});const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{const initial:Record<string,unknown>={};for(const f of config.fields){const existing=record?.fields[f.name];initial[f.name]=existing??(f.type==="checkbox"?false:f.type==="multi"?[]:"")}if(contextEvent&&config.fields.some(f=>f.name==="Event"))initial.Event=[contextEvent];if(contextClient&&config.fields.some(f=>f.name==="Client"))initial.Client=[contextClient];setValues(initial);const tables=[...new Set(config.fields.filter(f=>f.linkTable).map(f=>f.linkTable!))];Promise.all(tables.map(async t=>{const r=await fetch(`/api/airtable?table=${encodeURIComponent(t)}&pageSize=100`);const d=await r.json();return [t,d.records||[]] as const})).then(entries=>setLookups(Object.fromEntries(entries)))},[table,record,contextEvent,contextClient,config.fields]);
 const missing=useMemo(()=>config.fields.filter(f=>f.required).filter(f=>{const v=values[f.name];return Array.isArray(v)?!v.length:v===""||v==null}).map(f=>f.label||f.name),[values,config.fields]);
 async function submit(e:React.FormEvent){e.preventDefault();if(missing.length){setError(`Required: ${missing.join(", ")}`);return}setSaving(true);setError("");const fields:{[k:string]:unknown}={};for(const f of config.fields){let v=values[f.name];if(f.type==="number")v=v===""?0:Number(v);if(f.type==="attachment")v=v?[{url:String(v)}]:[];if(v!==""&&!(Array.isArray(v)&&!v.length))fields[f.name]=v}try{const res=await fetch('/api/airtable',{method:record?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table,id:record?.id,requestId:id(),fields})});const data=await res.json();if(!res.ok)throw new Error(typeof data.error==='string'?data.error:data.error?.message||'Unable to save');onSaved(data)}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setSaving(false)}}
 if(!config)return null;
 return <div className="record-form-overlay"><button className="record-form-scrim" onClick={onClose} aria-label="Cancel"/><form className="record-form" onSubmit={submit}><header><div><p className="eyebrow">AIRTABLE RECORD</p><h2>{record?`Edit ${config.title.replace('New ','')}`:config.title}</h2></div><button type="button" onClick={onClose}>×</button></header>{error&&<div className="form-error">{error}</div>}<div className="record-form-grid">{config.fields.map(f=><FormField key={f.name} field={f} value={values[f.name]} options={lookups[f.linkTable||""]||[]} onChange={v=>setValues(old=>({...old,[f.name]:v}))}/>)}</div><footer><button type="button" onClick={onClose}>Cancel</button><button className="gold-button" disabled={saving||missing.length>0}>{saving?'Saving…':record?'Save Changes':'Create Record'}</button></footer></form></div>
}

function FormField({field,value,options,onChange}:{field:Field;value:unknown;options:AirtableRow[];onChange:(v:unknown)=>void}){const label=field.label||field.name;if(field.type==="checkbox")return <label className="form-checkbox"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;if(field.type==="textarea")return <label className="form-wide"><span>{label}{field.required?' *':''}</span><textarea value={val(value)} onChange={e=>onChange(e.target.value)}/></label>;if(field.type==="select")return <label><span>{label}{field.required?' *':''}</span><select value={val(value)} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{field.options?.map(o=><option key={o}>{o}</option>)}</select></label>;if(field.type==="multi")return <fieldset className="form-wide"><legend>{label}</legend><div className="multi-options">{field.options?.map(o=><label key={o}><input type="checkbox" checked={Array.isArray(value)&&value.includes(o)} onChange={e=>onChange(e.target.checked?[...(Array.isArray(value)?value:[]),o]:(Array.isArray(value)?value:[]).filter(x=>x!==o))}/>{o}</label>)}</div></fieldset>;if(field.type==="link"){const current=Array.isArray(value)?value[0]:"";const primary=labels[field.linkTable||""]||"Name";return <label><span>{label}{field.required?' *':''}</span><select value={String(current||"")} onChange={e=>onChange(e.target.value?[e.target.value]:[])}><option value="">Search or select…</option>{options.map(r=><option key={r.id} value={r.id}>{String(r.fields[primary]||r.id)}</option>)}</select></label>}return <label><span>{label}{field.required?' *':''}</span><input type={field.type==="attachment"?"url":field.type||"text"} value={val(value)} min={field.type==="number"?0:undefined} onChange={e=>onChange(e.target.value)} placeholder={field.type==="attachment"?"https:// file URL":""}/></label>}
