import {NextRequest,NextResponse} from "next/server";
import {requireIdentity} from "../../../lib/auth";

type Row={id:string;fields:Record<string,unknown>};
const BASE=(process.env.AIRTABLE_BASE_ID||"").trim(),TOKEN=(process.env.AIRTABLE_TOKEN||"").trim();
const headers={Authorization:`Bearer ${TOKEN}`,"Content-Type":"application/json"};
async function records(table:string){const rows:Row[]=[];let offset="";do{const url=new URL(`https://api.airtable.com/v0/${encodeURIComponent(BASE)}/${encodeURIComponent(table)}`);url.searchParams.set("pageSize","100");if(offset)url.searchParams.set("offset",offset);const response=await fetch(url,{headers,cache:"no-store"});const data=await response.json() as {records?:Row[];offset?:string};if(!response.ok)throw new Error(`Unable to load ${table}`);rows.push(...(data.records||[]));offset=data.offset||""}while(offset);return rows}
function linked(row:Row,eventIds:string[]){const events=Array.isArray(row.fields.Event)?row.fields.Event as string[]:[];return events.some(id=>eventIds.includes(id))}
async function token(value:string){const secret=(process.env.EVENTART_PORTAL_SIGNING_SECRET||process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||"").trim();const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const signature=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value));return btoa(String.fromCharCode(...new Uint8Array(signature))).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,"")}
async function findByToken(rows:Row[],opaque:string){for(const row of rows)if(await token(row.id)===opaque)return row;return null}
function strings(value:unknown){return Array.isArray(value)?value.map(String):[]}

export async function GET(request:NextRequest){const auth=requireIdentity(request,["client"]);if(auth.error)return auth.error;const identity=auth.identity!;if(!identity.clientRecordId||!identity.eventRecordIds.length)return NextResponse.json({events:[]},{headers:{"Cache-Control":"private, no-store"}});if(!TOKEN||!/^app[A-Za-z0-9]{14}$/.test(BASE))return NextResponse.json({error:"Event data is not configured."},{status:503});try{const [events,budgets,items,payments,designs,guests,tables]=await Promise.all([records("Events"),records("Budgets"),records("Budget Items"),records("Payments"),records("Design Board"),records("Guests"),records("Seating Tables")]);const assigned=events.filter(event=>identity.eventRecordIds.includes(event.id)&&strings(event.fields.Clients).includes(identity.clientRecordId!));const seatingToken=request.nextUrl.searchParams.get("seating");if(seatingToken){const event=await findByToken(assigned,seatingToken);if(!event)return NextResponse.json({error:"This event is not available to your account."},{status:404});const eventGuests=guests.filter(row=>linked(row,[event.id]));const eventTables=tables.filter(row=>linked(row,[event.id]));const tableNames=new Map(eventTables.map(row=>[row.id,String(row.fields["Table Name"]||"Assigned table")]));return NextResponse.json({event:{name:event.fields["Event Name"],date:event.fields["Ceremony Date & Time"],venue:event.fields["Venue Name"]},guests:eventGuests.filter(row=>strings(row.fields["Seating Chart"]).length).map(row=>({name:String(row.fields["Full Name"]||`${row.fields["First Name"]||""} ${row.fields["Last Name"]||""}`).trim(),table:tableNames.get(strings(row.fields["Seating Chart"])[0])||"Assigned table",seat:row.fields["Seat Number"]||null,vip:Boolean(row.fields.VIP)}))},{headers:{"Cache-Control":"private, no-store"}})}
const result=[];for(const event of assigned){const eventBudgets=budgets.filter(row=>linked(row,[event.id]));const budgetIds=eventBudgets.map(row=>row.id);const visibleDesigns=designs.filter(row=>linked(row,[event.id])&&row.fields["Visible to Client"]===true);result.push({token:await token(event.id),name:event.fields["Event Name"],date:event.fields["Ceremony Date & Time"],venue:event.fields["Venue Name"],status:event.fields["Event Status"],theme:event.fields.Theme,colorPalette:event.fields["Color Palette"],budgets:await Promise.all(eventBudgets.map(async budget=>({token:await token(budget.id),name:budget.fields["Budget Name"],status:budget.fields.Status,proposalNumber:budget.fields["Proposal Number"],proposalDate:budget.fields["Proposal Date"],total:budget.fields["Total Client Price"],deposit:budget.fields["Deposit Required"],remaining:budget.fields["Remaining Balance"],items:items.filter(item=>strings(item.fields.Budget).some(id=>budgetIds.includes(id))&&item.fields["Included in Proposal"]===true).map(item=>({name:item.fields["Item / Service"],category:item.fields.Category,description:item.fields.Description,quantity:item.fields.Quantity,unitPrice:item.fields["Unit Price"],lineTotal:item.fields["Client Line Total"]}))}))),payments:payments.filter(row=>linked(row,[event.id])).map(row=>({type:row.fields["Payment Type"],amount:row.fields["Payment Amount"],date:row.fields["Payment Date"],dueDate:row.fields["Due Date"],status:row.fields["Payment Status"]})),designs:await Promise.all(visibleDesigns.map(async row=>({token:await token(row.id),title:row.fields["Design Title"],category:row.fields["Design Category"],approvalStatus:row.fields["Approval Status"],preview:row.fields["Preview Image"],files:row.fields["Design File"],link:row.fields["Design Link"],clientComments:row.fields["Client Comments"]})))})}return NextResponse.json({events:result},{headers:{"Cache-Control":"private, no-store"}})}catch(error){console.error("EventArt client portal error",{message:error instanceof Error?error.message:"Unable to load client portal"});return NextResponse.json({error:"Unable to load your EventArt portal."},{status:502})}}

export async function PATCH(request:NextRequest){const auth=requireIdentity(request,["client"]);if(auth.error)return auth.error;const identity=auth.identity!;const {designToken,comments}=await request.json() as {designToken?:string;comments?:string};if(!designToken||typeof comments!=="string"||comments.length>4000)return NextResponse.json({error:"Enter a comment of 4,000 characters or fewer."},{status:400});try{const designs=(await records("Design Board")).filter(row=>linked(row,identity.eventRecordIds)&&row.fields["Visible to Client"]===true);const design=await findByToken(designs,designToken);if(!design)return NextResponse.json({error:"This design is not available to your account."},{status:404});const response=await fetch(`https://api.airtable.com/v0/${encodeURIComponent(BASE)}/${encodeURIComponent("Design Board")}/${encodeURIComponent(design.id)}`,{method:"PATCH",headers,body:JSON.stringify({fields:{"Client Comments":comments},typecast:false})});if(!response.ok)return NextResponse.json({error:"Your comment could not be saved."},{status:502});return NextResponse.json({ok:true,message:"Your comment was saved."})}catch{return NextResponse.json({error:"Your comment could not be saved."},{status:502})}}
