import { NextRequest, NextResponse } from "next/server";
import { adminClient, requireIdentity, type EventArtRole } from "../../../../lib/auth";

type Body={action?:"invite"|"update"|"resend";userId?:string;name?:string;email?:string;role?:EventArtRole;active?:boolean;clientRecordId?:string;eventRecordIds?:string[]};
const roles=new Set(["owner","team","client"]);
const recordId=(value:string)=>/^rec[A-Za-z0-9]{14}$/.test(value);

export async function GET(request:NextRequest){const auth=requireIdentity(request,["owner"]);if(auth.error)return auth.error;try{const client=adminClient();const {data:profiles,error}=await client.from("profiles").select("user_id,name,email,role,active,client_record_id,created_at").order("created_at");if(error)throw error;const {data:access,error:accessError}=await client.from("user_event_access").select("user_id,event_record_id");if(accessError)throw accessError;return NextResponse.json({users:(profiles||[]).map(profile=>({...profile,eventRecordIds:(access||[]).filter(row=>row.user_id===profile.user_id).map(row=>row.event_record_id)}))},{headers:{"Cache-Control":"private, no-store"}})}catch(error){console.error("EventArt user management error",{message:error instanceof Error?error.message:"Unable to load users"});return NextResponse.json({error:"Unable to load EventArt users. Confirm the Supabase migration has been applied."},{status:502})}}

export async function POST(request:NextRequest){const auth=requireIdentity(request,["owner"]);if(auth.error)return auth.error;let body:Body;try{body=await request.json()}catch{return NextResponse.json({error:"Invalid request."},{status:400})}try{const client=adminClient();if(body.action==="invite"){const email=body.email?.trim().toLowerCase();const name=body.name?.trim();if(!email||!name||!body.role||!roles.has(body.role))return NextResponse.json({error:"Name, email and role are required."},{status:400});const events=(body.eventRecordIds||[]).filter(recordId);const redirect=(process.env.EVENTART_APP_URL||request.nextUrl.origin).replace(/\/$/,"")+"/auth/callback";const {data,error}=await client.auth.admin.inviteUserByEmail(email,{redirectTo:redirect,data:{name}});if(error||!data.user)return NextResponse.json({error:error?.message||"Unable to send invitation."},{status:400});const {error:profileError}=await client.from("profiles").upsert({user_id:data.user.id,name,email,role:body.role,active:true,client_record_id:body.role==="client"&&body.clientRecordId&&recordId(body.clientRecordId)?body.clientRecordId:null});if(profileError)throw profileError;if(events.length){const {error:eventError}=await client.from("user_event_access").insert(events.map(event_record_id=>({user_id:data.user.id,event_record_id})));if(eventError)throw eventError}return NextResponse.json({ok:true,message:"Secure invitation sent."},{status:201})}
if(body.action==="resend"){if(!body.email)return NextResponse.json({error:"Email is required."},{status:400});const redirect=(process.env.EVENTART_APP_URL||request.nextUrl.origin).replace(/\/$/,"")+"/auth/callback";const {error}=await client.auth.admin.inviteUserByEmail(body.email,{redirectTo:redirect});if(error)return NextResponse.json({error:"The provider could not resend this invitation. The user may already have accepted it."},{status:400});return NextResponse.json({ok:true,message:"Invitation resent."})}
return NextResponse.json({error:"Unsupported action."},{status:400})}catch(error){console.error("EventArt invitation error",{message:error instanceof Error?error.message:"Unable to manage user"});return NextResponse.json({error:"Unable to complete user management. No Airtable data was changed."},{status:502})}}

export async function PATCH(request:NextRequest){const auth=requireIdentity(request,["owner"]);if(auth.error)return auth.error;const body=await request.json() as Body;if(!body.userId||!body.role||!roles.has(body.role))return NextResponse.json({error:"User and role are required."},{status:400});if(body.userId===auth.identity!.userId&&body.active===false)return NextResponse.json({error:"You cannot disable your own owner account."},{status:409});try{const client=adminClient();const events=(body.eventRecordIds||[]).filter(recordId);const profile={role:body.role,active:body.active!==false,name:body.name?.trim(),client_record_id:body.role==="client"&&body.clientRecordId&&recordId(body.clientRecordId)?body.clientRecordId:null,updated_at:new Date().toISOString()};const {error}=await client.from("profiles").update(profile).eq("user_id",body.userId);if(error)throw error;const {error:deleteError}=await client.from("user_event_access").delete().eq("user_id",body.userId);if(deleteError)throw deleteError;if(events.length){const {error:eventError}=await client.from("user_event_access").insert(events.map(event_record_id=>({user_id:body.userId,event_record_id})));if(eventError)throw eventError}return NextResponse.json({ok:true,message:profile.active?"Account access updated.":"Account disabled."})}catch(error){console.error("EventArt user update error",{message:error instanceof Error?error.message:"Unable to update user"});return NextResponse.json({error:"Unable to update this account."},{status:502})}}
